---
title: Costs and Getting Access
---

## Getting access
### Uploading data

All VU employees can create an account in DataverseNL and upload and publish datasets. When you wish to upload data to DataverseNL, it is important to select your faculty or department. If you want to upload your dataset as part of a certain department, and your department is not yet included in DataverseNL, you can contact the DataverseNL manager to request your department to be added. You can use the Contact button in DataverseNL to submit such a request.

### Viewing and reusing data

Data that are publicly available, are visible and downloadable for everyone. 

If a dataset includes files with restricted access, people interested in the data have to create an account in DataverseNL to be able to request access to those files. The contact person for the dataset needs to grant access in order for others to use the data.
 
## Are there costs involved?
The costs for archiving datasets for the required period stated in the [Research Data and Software Management Policy](https://rdm.vu.nl/guides/policies-supporting-vision-open-science.html) are currently covered through the Cost Recharge Model (KDM). The details can be found in the 🔒 [Research Archiving & Storage Cost Model](https://vu.nl/en/employee/research-data-support/research-archiving-storage-cost-model). 