---
title: Quick Start
---

### Creating an account

DataverseNL can be accessed via SURFconext. Make sure to [log in](https://dataverse.nl/loginpage.xhtml?redirectPage=dataverseuser.xhtml) with your institution credentials. 


### Uploading data

To deposit or publish data, you need permissions from the Vrije Universiteit. Please contact [RDM support desk](mailto:rdm@vu.nl)to request access to create and upload dataset.

It is important to select your faculty or department when uploading data to DataverseNL. If you want to upload your dataset as part of a certain department, and your department is not yet included in DataverseNL, you can contact the DataverseNL manager to request your department to be added. You can use the Contact button in DataverseNL to submit such a request.


### Viewing and reusing data

Data that are publicly available, are visible and downloadable for everyone. 

If a dataset includes files with restricted access, people interested in the data have to create an account in DataverseNL to be able to request access to those files. The contact person for the dataset needs to grant access in order for others to use the data.
 

For practical information please visit the [DataverseNL website](https://dans.knaw.nl/en/data-services/dataversenl/user-guide/).
