project:
  type: website

website:
  site-url: "https://ubvu.github.io/open-handbook"
  title: "Research Support Handbook"
  description: "A place for all things open research at VU Amsterdam."
  favicon: public/favicon.png
  repo-url: https://github.com/ubvu/open-handbook
  issue-url: https://github.com/ubvu/open-handbook/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  search: 
    location: navbar
    type: textbox
  navbar:
    background: "#0077b3"
    logo: public/VU-logo-white.svg
    logo-alt: "VU Amsterdam logo."
    # title: "Open Handbook"
    title: false
    collapse-below: lg
    left:
      - text: "Topics"
        menu:
          - text: All
            file: topics.qmd
          - text: Policies and Legislation
            href: /topics.html#category=Policies%20and%20Legislation
          - text: Research Data
            href: /topics.html#category=Research%20Data
          - text: Research Software
            href: /topics.html#category=Research%20Software
          - text: Responsible Scholarship
            href: /topics.html#category=Responsible%20Scholarship
          - text: Knowledge Items
            href: /topics.html#category=Knowledge%20Items
      - text: Guides
        file: guides.qmd
      - text: Tools
        file: tools.qmd
      - text: News
        file: blog.qmd
    tools:
      - icon: github
        href: https://github.com/ubvu/open-handbook
        text: GitHub VU Open Handbook
      # - icon: rss
      #   href: https://quarto.org/docs/blog/index.xml
      #   text: Quarto Blog RSS

bibliography: references.bib

language: 
  search-text-placeholder: Search

resources:
  - "public/*"
  - CNAME
format:
  html:
    toc: true
    theme:
      - cosmo # https://bootswatch.com/
      - custom.scss # https://quarto.org/docs/output-formats/html-themes.html#theme-options
    code-copy: true
    code-overflow: wrap
    link-external-icon: false
    include-before-body: 
      text: |
        <div class="handbook-title">Research Support Handbook</div>
# from: "markdown+emoji"
filters:
  - utils/include-files.lua
  - utils/linktarget.lua
execute:
  freeze: auto

metadata-files:
  - _footer.yml
  - tools/ada/_sidebar.yml
  - tools/dataversenl/_sidebar.yml
  - tools/dmponline/_sidebar.yml
  - tools/ithenticate/_sidebar.yml
  - tools/nebula/_sidebar.yml
  - tools/osf/_sidebar.yml
  - tools/pure/_sidebar.yml  
  - tools/qualtrics/_sidebar.yml
  - tools/researchcloud/_sidebar.yml
  - tools/researchdrive/_sidebar.yml
  - tools/scicloud/_sidebar.yml
  - tools/scistor/_sidebar.yml
  - tools/scisure/_sidebar.yml
  - tools/snellius/_sidebar.yml
  - tools/vucomputehub/_sidebar.yml
  - tools/yoda/_sidebar.yml