---
title: Deleting and Migrating your Account
---

::: {.callout-important}
VU Amsterdam advises researchers to no longer start new projects in OSF. The project functionality will cease to work as of **19 February 2027**. Any projects expected to be active at that time will have to move to alternative tools in order to keep sharing research documents with colleagues. 

The OSF pre-registration and pre-print functionality will remain unchanged.

For further information, contact: [osfadmin@vu.nl](mailto:osfadmin@vu.nl)
:::

## Retaining access to your data when leaving VU Amsterdam

If you want to retain access to your OSF Projects after leaving VU Amsterdam, you can create a new OSF account with a personal email address and merge it with your institutional account (see the [OSF Guide](https://help.osf.io/hc/en-us/articles/360019738014-Merge-Your-Accounts)). Make sure to do this before your VUnetID expires. 

If your VUnetID has already expired, you can still create a new OSF account and ask a Project Admin to re-add you to your Projects.

If your VUnetID has expired and you are the only Project Admin please contact [OSF Support](https://help.osf.io/hc/en-us/requests/new).

### Deleting your account

You can deactivate or delete your OSF account at any time. To permanently delete your account and personal data, please contact [OSF Support](mailto:support@osf.io).
