---
title: Connecting Storage and Apps
---

OSF allows you to connect to other storage platforms and services via Add-ons, see the [OSF Add-ons and integrations Guide](https://help.osf.io/article/395-storage-add-ons) for more information. Storage Add-ons are particularly well suited for data sharing in a project. However, please consider the following when adding them to your project: 

* what data (folders) is being shared 
* who this resource is being shared with 
* who manages the Add-on (e.g. how long will it be available)

Recommended connected storage options are [Research Drive](https://services.vu.nl/esc?id=sc_cat_item&sys_id=39d345f097066990e553359fe153af01) ([how-to guide](https://osf.io/4ewgx/)) and [SURFdrive](https://services.vu.nl/esc?id=emp_taxonomy_topic&topic_id=fb4eda9f978f09d0e553359fe153afa5) ([how-to guide](https://osf.io/e9a5v/)). The VU discourages using Dropbox and Google Drive for storing research data.

For projects that include code, connecting to GitHub repository is recommended. To do so please follow the steps in the [OSF Guide](https://help.osf.io/hc/en-us/articles/360019929813-Connect-GitHub-to-a-Project). If you only wish to publish a GitHub repository, consider using [Zenodo](https://guides.github.com/activities/citable-code/).

You can also connect a dataset from [DataverseNL](/tools/dataversenl/index.qmd) to your project, allowing published datasets to be viewed directly within OSF. It is possible to [upload and delete](https://osf.io/w2sme/) files from datasets that are still in Draft.

Please note that anyone with access to your OSF project will also be able to view the files in any connected storage location, even if those files have not been explicitly shared on the original platform. 
