---
title: Support and Contact
---

::: {.callout-important}
VU Amsterdam advises researchers to no longer start new projects in OSF. The project functionality will cease to work as of **19 February 2027**. Any projects expected to be active at that time will have to move to alternative tools in order to keep sharing research documents with colleagues. 

The OSF pre-registration and pre-print functionality will remain unchanged.

For further information, contact: [osfadmin@vu.nl](mailto:osfadmin@vu.nl)
:::

The following hierarchy of support options is available if you run into problems or have questions about using the OSF.

1.  Try the [OSF Guides](https://help.osf.io/) first, they are quite extensive. Quick start up guide for VU OSF users is available in the section [Quick Start](quick_start.qmd).

2.  If the answer to your question is not in the OSF Guides or if you run into a technical problem, you can contact OSF support directly via [the contact form](https://help.osf.io/hc/en-us/requests/new). As a member of OSF institutions, VU users receive priority support.

3.  Contact the [RDM Support Desk](mailto:rdm@vu.nl?subject=OSF) if you have questions with regard to the operation of VU OSF or more general questions about Research Data Management.
