---
title: Costs and Getting Access
---

## How to get access?

If you like to start with OSF please go to: [OSF](https://osf.io/).

You can either create a new OSF account and choose \"Sign up using Institution\" and select Vrije Universiteit Amsterdam [(OSF Guide)](https://help.osf.io/article/271-create-an-osf-account). VU researchers can make use of OSF by logging in with their VUnetID credentials (SSO). The OSF account will be automatically created. Or you can add your VUnetID login to your existing OSF account [(OSF Guide)](https://help.osf.io/article/238-add-a-new-email-address-to-your-account). If you already have an OSF account and would like to affiliate this to
VU Amsterdam, please visit: [Affiliate an OSF Project with an Institution - OSF Support](https://help.osf.io/article/192-affiliate-an-osf-project-with-an-institution) and registrations with the VU ([OSF Guide](https://help.osf.io/hc/en-us/articles/360019738394-Affiliate-a-Registration-with-an-Institution)).

When the OSF account is created, you can start directly with using OSF to create a project, registering your preregistration or publishing using the preprints options at OSF (see the section [What it can be used for?](index.qmd#what-can-it-be-used-for)).

### Access for students

Students are also welcome to use OSF. Note that logging in with VUnetID requires MFA via de SURFsecureID (with the tiqr app or a YubiKey). [Secure sign on - MS Authenticator activation for SURF Secure ID](https://services.vu.nl/esc?id=kb_article&table=kb_knowledge&sys_id=648865b4874bc15010be65b40cbb3592&recordUrl=%2Fkb_view.do%3Fsys_kb_id%3D648865b4874bc15010be65b40cbb3592) has more information on how to register for MFA if you have not already done so.

## Are there costs involved?

The costs for storing data in OSF are detailed on the [VU website](https://vu.nl/en/employee/research-data-support/research-archiving-storage-cost-model).

OSF storage has a limit of 5GB for a private project and 50GB for a public project. Note that it is possible to request additional (paid) OSF storage via the [Request form](https://docs.google.com/forms/d/1CImattWD9KdefK-vFmMbB1I0pfl4FkKj0e1fNgz0AG4/viewform?edit_requested=true). More information on available storage tiers can be found on the [Supporting OSF Usage page](https://www.cos.io/osf-usage). Another way to acquire more storage is connecting an alternative storage provider via Add-ons as described in [Connecting storage and apps](https://rdm.vu.nl/guides/use-osf.html#connecting-storage-and-apps). The [OSF storage caps page](https://help.osf.io/hc/en-us/articles/360054528874-OSF-Storage-Caps) has more information on extending storage capacity.