---
title: Preregistration
---

## What is preregistration?

Preregistration is the practice of specifying in advance how data will be collected and analysed. These plans are documented in time-stamped, immutable records, ensuring transparency and accountability in the research process. By clearly outlining hypothesis and methods beforehand, preregistration helps distinguish between hypothesis testing, conﬁrmatory research and hypothesis generating research. This distinction is crucial, as presenting exploratory findings as confirmatory may increase the publishability of results, but does so at the expense of their credibility. You can read more about this in the [Preregistration topic](/topics/pre-registration.qmd).

## How to preregister?

The [Preregistration Challenge](https://www.cos.io/initiatives/prereg-more-information) was an education campaign designed to introduce preregistration as a regular habit. It includes a guided workﬂow to help you create a preregistration.

See the [COS Preregistration page](https://www.cos.io/initiatives/prereg) for more information about preregistration and start working on your own preregistration in [OSF Registries](https://osf.io/registries).

## Resources and Further Readings

* Preregistration is also possible if you are using existing data. Templates are available at [OSF Registries](https://osf.io/registries).
* The [Preregistration Revolution](https://doi.org/10.1073/pnas.1708274114) covers nine scenarios in which preregistration is beneficial.
* You can visit [the blog series](https://www.cos.io/blog/tag/preregistration) on preregistration by the Center for Open Science. 
* The Guardian: [Trust in science would be improved by study pre-registration](https://www.theguardian.com/science/blog/2013/jun/05/trust-in-science-study-pre-registration).
* Nature: [A manifesto for reproducible science](https://doi.org/10.1038/s41562-016-0021).
* You can visit this [OSF presentation](https://osf.io/dh62a/) introducing the platform. 
* You can visit this [OSF presentation](https://osf.io/zxmkf/) on creating your first project in OSF. 
