---
title: Quick Start
---

To get started with OSF please visit the [Getting started on the OSF (Video) - OSF Support](https://help.osf.io/article/342-getting-started-on-the-osf). You can also subscribe to the onboarding webinars [OSF \| Trainings and Webinars](https://www.cos.io/osf-onboarding?utm_source=osf_onboarding&utm_medium=email&utm_campaign=welcome).

You can either create a new OSF account and choose `Sign up using Institution` and select `Vrije Universiteit Amsterdam` (see the [OSF Guide](https://help.osf.io/article/271-create-an-osf-account)). VU researchers can make use of OSF by logging in with their VUnetID credentials (SSO). The OSF account will be automatically created. It is also possible to link your credentials to your existing OSF account (see the [OSF Guide](https://help.osf.io/article/238-add-a-new-email-address-to-your-account)).

If you already have an OSF account and would like to affiliate this to
VU Amsterdam, please visit the page [Affiliate an OSF Project with an Institution](https://help.osf.io/article/192-affiliate-an-osf-project-with-an-institution) and the page [Affiliate an OSF Registration with an Institution](https://help.osf.io/hc/en-us/articles/360019738394-Affiliate-a-Registration-with-an-Institution).

When the OSF account is created, you can start directly with using OSF to create a project, registering your preregistration or publishing using the preprints options at OSF (see the section [What it can be used for?](index.qmd#what-can-it-be-used-for)).

Once a year, there will be an OSF workshop organised by VU application managers, where you learn how you can use OSF. See the [Trainings page](/trainings.qmd#open-science-framework-osf-workshop) for training materials and scheduled workshops. 

### Information for New Users
Many manuals are available for users starting with OSF. They are listed below for the different types of functionality that [OSF](https://www.cos.io/blog/getting-started-osf?utm_source=dsa&utm_medium=google&utm_campaign=ad&utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&hsa_acc=5222345373&hsa_cam=22239125465&hsa_grp=176557684282&hsa_ad=733019716287&hsa_src=g&hsa_tgt=dsa-2401106406195&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gad_campaignid=22239125465&gbraid=0AAAAADluZIu8mAcNrxefsqZmNojtRQ8d7&gclid=Cj0KCQjwj47OBhCmARIsAF5wUEHV_ADYftMCpKetYqFvqks7C-CbArYejZUCMSC5MUPwdAD4nSdBpL8aAmoBEALw_wcB) provides.

#### File Management and Licensing

* [File naming (OSF Projects) - OSF Support](https://help.osf.io/article/146-file-naming)
* [Organising files (OSF Projects) - OSF Support](https://help.osf.io/article/147-organizing-files) 
* [Licensing - OSF Support](https://help.osf.io/article/148-licensing) 
* Version Control [Version Control - OSF Support](https://help.osf.io/article/149-version-control)

#### Research Design

* Preregistration [Preregistration - OSF Support](https://help.osf.io/article/145-preregistration)
* Creating a data management plan (DMP) [Creating a data management plan (DMP) document - OSF Support](https://help.osf.io/article/144-creating-a-data-management-plan-dmp-document)

#### Handling Data

* How to Make a Data Dictionary [How to Make a Data Dictionary - OSF Support](https://help.osf.io/article/217-how-to-make-a-data-dictionary)
* Sharing Research Outputs [Sharing Research Outputs - OSF Support](https://help.osf.io/article/219-sharing-research-outputs)
* Sharing data [Data Management - OSF Support](https://help.osf.io/article/392-data-management)

#### Preprints

* [Welcome to OSF Preprints (Video) - OSF> Support](https://help.osf.io/article/376-preprints-home-page)

#### Creating and Managing OSF Projects

* [Managing projects (OSF Projects) - OSF> Support](https://help.osf.io/article/384-managing-projects)

### The Open Scholarship Knowledgebase (OSKB)

Resource guides on reproducibility: [oercommons.org/curated-collections/1038](http://oercommons.org/curated-collections/1038)

### Curated Reading List of Metascience

The Center for Open Science (COS) has compiled a list of papers related to the need for more transparent research and the effectiveness of such research practices. You can find the list on their [Open Science Literature page](https://osf.io/kgnva/wiki/Open%20Science%20Literature/). The list includes literature on the following aspects:

* Beneﬁts of transparency
* Data sharing policies and practices
* Reporting Standards, Guidelines, and Checklists
* Effects of preregistration or Registered Reports
* Questionable research practices
* The Reproducibility Crisis
* Evaluating Journals Policies
* Recommendations for Increasing Reproducibility
* Attitudes about open science

### Overcoming the Knowledge Barrier

On their page [Overcoming the Knowledge Barrier](https://osf.io/bk6r7/wiki/home/), the Center for Open Science provides a lot of information to get started with an open and reproducible research practice. This page lists a lot of resources to get you up to speed with open science practices:

* Primers on implementing open science practices
* Tutorials and online curricula for coded statistical analysis
* Links to open science communities

### Center for Open Science content

* [Blog series](https://www.cos.io/blog)
* [Webinars](https://www.cos.io/events)
* [Resources for researchers](https://www.cos.io/communities/scientists-and-researchers)


