---
title: Buying dedicated nodes
---
If your research projects require heavy usage of HPC you can consider spending part of your research budget to buy compute hardware (nodes) for your group. 

The nodes will be hosted in the ITvO data center and added to the ADA cluster. [IT for Research (ITvO)](/topics/itvo.qmd) manages the OS, base software environment, access model and user access.

Please contact [IT for Research (ITvO)](/topics/itvo.qmd#contact) to discuss adding dedicated nodes for your group. ITvO can help you find the best hardware for your budget and will order the hardware for you via the central IT department.

## Requirements hardware for ADA HPC
To make sure the hardware fits in the existing cluster it must meet certain requirements:

- be rear I/O configured.
- have a modern generation of PCIe expansion slots.
- have an IPMI (network card).
- fit into a 42U 19-inch rack.
- be compatible with the current ITvO network infrastructure.
- have a redundant 80 PLUS power supply unit (PSU) that is titanium certified.
- be ordered with a network cable included.
- be air cooled.
- have a minimum of 2 NVMe disks for scratch space.
- not contain any consumer grade GPU’s (data center verified only).

ITvO further recommends the following specifications:

- The server is configured with all RDIMM slots occupied as necessary for maximum CPU performance (e.g. 12 for most zen5 AMD chips).
- Possible future expansion of GPU/memory is taken into account when ordering the chassis configuration.
- A warranty of at least 3 year on the purchased hardware.

## User policy for adding own hardware to ADA HPC
Besides the hardware requirements the following policies apply to dedicated nodes:

### Warranties & maintenance
- Within the warranty period, replacement and/or repairs of the hardware are possible and will be reimbursed by the supplier. After the warranty period has passed, replacing and/or repairing hardware will be done at your own expense. Any required support from ITvO for this will be done on a best effort basis.

### Delivery of hardware ordered via IT
- If the product does not meet the requirements (i.e. defective, not the ordered product), it can be returned to the supplier based on the supplier’s return policy.

- ITvO cannot guarantee delivery within a financial year, because this depends on suppliers and procurement processes. ITVO cannot be held responsible for any delays. 

### Existing hardware
- If a researcher moves from another institute to the VU, equipment may be relocated as well, provided that it meets the VU’s requirements. The [IT for Research team](/topics/itvo.qmd) can provide advice and assistance in this process. 

- In case the hardware would create disproportionate operational maintenance, ITVO is entitled to reject it.

### Ownership
- The user will maintain the right to remove the hardware if it has been funded from their own resources. If the hardware has been funded by the VU, the hardware will remain VU property.

### Disposing of old hardware
- Any defective hardware will be disposed of according to IT policy.
