---
title: Costs and Getting Access
---

## How to request access
### Creating and Accessing User Accounts

VU Amsterdam Qualtrics Central Brand at [vuamsterdam.eu.qualtrics.com](https://vuamsterdam.eu.qualtrics.com) allows for user's auto-enrolment, an automated account creation and registration process. Any user with an enabled VU or ACTA email address may auto-enroll on VU's Central Brand. The email address will function as the account's username.

[VU's Central Brand](https://vuamsterdam.eu.qualtrics.com) makes use of Single-Sign On (SSO). This means that users can log in to Qualtrics using their VU credentials. Multi-Factor Authentication (MFA) is required for all users, including employees, researchers, and students. Please note that MFA is not enabled by default for students and may require activation via the IT Service Desk. 


## Are there costs involved?

There are no costs involved. All students and researchers with a VU or ACTA email address can use Qualtrics for scientific purposes.
