---
title: Qualtrics
categories: [Online surveys]
image: '/public/qxm_color.svg'
aliases: 
    - "/topics/qualtrics.html"
    - "/manuals/qualtrics/index.html" 
---

## What is it?

Qualtrics is a cloud-based subscription and software platform (SaaS) that enables users to create and manage online surveys. The Qualtrics survey tool can support a variety of (complex) survey design requirements by providing such functionalities as different question types, display and branching logic configuration and the use of embedded data and APIs.

## What can it be used for?

All VU students, employees and researchers are eligible to make use of a Qualtrics licence. VU's Qualtrics licence usage is limited for creating, managing and collecting data for scientific research purposes only.

Qualtrics should not be used for non-scientific purposes such as the creation of registration or attendance lists and course evaluation surveys for example; instead users should go to other available tools such as [MS Forms](https://www.microsoft.com/en-us/microsoft-365/online-surveys-polls-quizzes).

VU Amsterdam holds an academic licence which includes non-standard, advanced features and functions, including but not limited to:

* **FILE UPLOAD** – a non-standard question type that allows respondents to upload a file along with their survey response
* **SIGNATURE QUESTION** – a non-standard question type that presents survey participants with an entry box where they can draw their signature.
* **API INTEGRATION** – an advanced licence feature that can be used to automate repetitive processes inside of Qualtrics or to pass information in and out of Qualtrics.
* **OFFLINE SURVEY APP** – an advanced licence feature that comprises a downloadable application available for iOS and Android that allows you to administer surveys on your mobile device or tablet without an internet connection.


