---
title: Working Securely
categories: []
---

## Working with Personal Data  and GDPR Compliance

When conducting research with Qualtrics, you will often collect and process [personal data](https://rdm.vu.nl/topics/gdpr.html#definitions). Personal data is protected under the General Data Protection Regulation (GDPR).

When using Qualtrics to collect research data, GDPR compliance should be considered from the start of the project. Researchers must ensure that personal data are collected on a valid legal ground, that participants are properly informed, and that the subject's rights are upheld. Depending on the study, additional requirements such as a DPIA or data sharing agreements may apply. Please refer to this [GDPR guidance page](https://rdm.vu.nl/guides/comply-with-gdpr.html) for more information on how to comply with GDPR requirements in research.

## Qualtrics Features and GDPR Considerations

Qualtrics offers a wide range of features that can influence how personal data is collected, processed, stored, shared, or transferred.

The sections below highlight several of the most commonly used features within the organisation and explain their potential GDPR implications. However, this overview is not exhaustive. Other Qualtrics functionality, settings, integrations, or design choices may also affect the processing of personal data. 

Researchers should therefore carefully consider the privacy implications of the features they enable, and the survey configurations they choose. As a general principle, privacy and data protection considerations should be assessed whenever selecting or configuring Qualtrics functionality for research purposes.

## After Collecting Your Data: Please Consider an Appropriate Data Storage Tool

Qualtrics is intended for the collection and management of survey data and should not be used as a data storage platform.

When data collection is completed, please delete all data from Qualtrics as soon as possible. It is strongly recommended that all research data is transferred three months after data collection is completed at the latest. 

**Transfer** all data from Qualtrics to an appropriate [data storage](https://rdm.vu.nl/topics/data-storage.html) solution and make sure to **delete** the data in Qualtrics as soon as the transfer is completed. The Data Storage Finder can assist you in finding appropriate storage platforms and you can contact your Faculty Data Steward or the RDM Support Desk if you need more advice on this.

Following the above, Qualtrics should never be used as an archive for long-term storage of your data after your research has been completed.
