---
title: iThenticate
categories: [Plagiarism Detection]
aliases:
    - "/topics/ithenticate.html"
    - "/manuals/ithenticate/index.html"
image: '/public/logo-ithenticate.svg'
---

## What is it?
iThenticate is plagiarism detection software that compares a researcher's original work with published academic work available online, and bibliographical databases such as Crossref. The tool scans for text similarity between the original work and published work, resulting in a similarity score. Every similarity found by iThenticate can be analysed, enabling the researcher to look at the specific text and location of the original work.

## What can it be used for?
iThenticate is used by researchers to ensure the originality of written work before publication. The approach to plagiarism checks at VU is not primarily for retrospective detection but is rather employed in an educational and preventative manner, explicitly aiming to enhance awareness of scientific integrity in accordance with the [Netherlands Code of Conduct for Research Integrity (NGWI)](https://www.nwo.nl/en/netherlands-code-of-conduct-for-research-integrity).

Starting from September 1, 2022, PhD candidates who commence their PhD research are required to conduct an initial scan in iThenticate early in their trajectory. The educational aspect involves discussing the results of the scan with their supervisor. The goal is to educate VU PhD candidates to become engaged and responsible scientific researchers.
