---
title: Costs and Getting Access
---

## How to request access
Requesting a project folder in Yoda is done via a 🔒 [request form on ServiceNow](https://services.vu.nl/esc?id=sc_cat_item&sys_id=20436ee397c6a910e553359fe153aff1).Please note that because there can be costs involved (see below) you need to supply a budget code.

Once the project space has been created you can start to invite your collaborators yourself. Note that VU students must 🔒 [connect a token to SURFsecureID](https://services.vu.nl/kb_view.do?sysparm_article=KB0011809) to be able to log in.

### Intake procedure
When you work with sensitive data we will always schedule a meeting with you to help you to safely work with your data.

In the form you can also indicate if you would like some help getting started with Yoda. We can either schedule a short
15 minute meeting to get you started or a longer meeting to have a closer look at your data and help you setting up a workflow.


## Are there costs involved?
The costs of storing data in Yoda are detailed on the 🔒 [VU website](https://vu.nl/en/employee/research-data-support/research-archiving-storage-cost-model). 