---
title: Before Getting Started
categories: []
---

There are three main ways to transfer data to and from Yoda. Note that creating a data access password is necessary to transfer data from and to Yoda.

You can transfer files to and from Yoda dependent on the size and number of files: 

- For small amounts of data (typically up to 10GB, up to 100 files) you can upload files via the Drag & Drop via de Yoda Portal. 
- For larger amounts of data (typically up to 100GB, up to 1000 files) it is better to use the WebDAV interface.
- For very large amounts of data you can connect directly to iRODS.

::: {.callout-tip}
For practical tips on working with your data, check the [Analysing Data](analysing_data.qmd) page.
:::

## Access via WebDAV
There are several methods to access Yoda data via WebDAV, they depend on the Operating System you are using:

- [Windows](data_access_windows.qmd)
- [MacOS](data_access_macos.qmd)
- [Linux](data_access_linux.qmd)

## Access via iRODS
For transferring large amounts of data (>100GB) consider using direct access to iRODS. A direct iRODS connection offers better performance by enabling multi-threaded transfers and the option to compare checksums.

Power users who are comfortable with command line tools can use the [iRODS iCommands](yoda_using_icommands.html) to interact with the iRODS backend of Yoda directly. If iCommands are not available on your OS, [Gocommands](yoda_using_gocommands.qmd) can be used as an alternative.