---
title: Quick Start
---

Before getting started, a project space must be created and a user account must be added by the Yoda administrator before a user has access to Yoda. Whilst Yoda leverages on a user’s VUnetID as an authentication and identification mechanism, single sign-on (SSO), users should always use their primary e-mail address to login to the [Yoda Web Portal](https://portal.yoda.vu.nl/).


After recieving an inviation, you can [accept](https://rdm.vu.nl/tools/yoda/sram_invitations_eduid_activation.html) the invitation to proceed to [log in](https://rdm.vu.nl/tools/yoda/logging_in.html) to the system. Depending on your access rights you may [invite](https://rdm.vu.nl/tools/yoda/group_manager.html) other users to the project space. 

Yoda allows its users to [search](https://rdm.vu.nl/tools/yoda/finding_restoring.html) for certain data files or [restore](https://rdm.vu.nl/tools/yoda/finding_restoring.html) older file versions. (maybe not too relevant for a quick start?)

You can visit [Metadata](https://rdm.vu.nl/tools/yoda/metadata.html) for more information about adding metadata and [selecting](https://rdm.vu.nl/tools/yoda/workflow_metadata_license.html) a license for your dataset. 

To access data and transfer data to Yoda a [data access password] should be created. Depending on the Operating System you are using, differenet  For more information on accessing data and data transfer you can visit [Data Access and Transfer](

After completion of your research you can [archive](https://rdm.vu.nl/tools/yoda/vault_archive.html) and [publish](https://rdm.vu.nl/tools/yoda/vault_publish.html) your data. 




## Documentation on other sites

More information can be found on the [SURF User Knowledge base](https://servicedesk.surf.nl/wiki/display/WIKI/Yoda+Hosting).

The [Yoda site of Utrecht University](https://www.uu.nl/en/research/Yoda) also contains useful information and is being redeveloped so it can also be used by VU Amsterdam and the other Consortium Partners.
