# Example chapter

This is an example chapter. We can also add references [@knuth84] or inline references @knuth84.

## Section

This is an example section. Once you include a section this way there will be a table of contents on the page too!

You can use all kinds of helpful tools to highlight information - these are called "Callouts"


::: {.callout-note}
Note that there are five types of callouts, including:
`note`, `warning`, `important`, `tip`, and `caution`.
:::

::: {.callout-warning}
## Warning with Title

This is an example of a callout with a title.
:::

::: {.callout-important}
## important with Title

This is an example of a callout with a title.
:::


::: {.callout-tip}
## Tip with Title

This is an example of a callout with a title.
:::

::: {.callout-caution collapse="true"}
## Expand To Learn About Collapse

This is an example of a 'folded' caution callout that can be expanded by the user. You can use `collapse="true"` to collapse it by default or `collapse="false"` to make a collapsible callout that is expanded by default.
:::

