---
title: FAQ
categories: []
description: "Frequently asked questions about GitLab"
---

### What is GitLab?

GitLab is a web-based platform for version control and collaboration on code-based projects. It enables researchers to store, manage, and share code, track changes over time, and collaborate with others using Git repositories.

### Do I need to create an account?

VU users do not need to create an account. You can simply visit the [Gitlab websiste](https://git.vu.nl/). Non-VU users need to request access. You ca request an account by contacting (). 

### I am an external user, how can I access Gitlab?
You can request access to Gitlab by contacting (). 

### How to add colllabs?
To add collaborators in GitLab, open your project, go to Manage > Members, and click Invite members to assign user roles and grant access. 

### What is the difference between public, private and internal projects?
Public project can be viewed by all VU users. Private projects can be restricted to to invited members.  
### Can I put personal data on Gitlab?

### Can I use actions in Gitlab?

### Which rights can I have for my projects?

### What the difference between Gitlab and Github?

### How to transfer a project from Github to Gitlab?

### Can I work on my project in both Github and Gitlab simultaneously?
