---
title: GitLab
categories: [Compute]
---

## What is it?
GitLab is a web-based platform for version control and collaboration on code-based projects. It enables researchers to store, manage, and share code, track changes over time, and collaborate with others using Git repositories.


## What can it be used for?
GitLab can be used to support the development and management of code-based research projects. Common use cases include:

- Version control of code and scripts: Track changes over time, revert to previous versions, and maintain a clear history of your work.

- Collaboration on research projects: Work together with colleagues on shared codebases, contribute changes, and review each other’s work.

- Project management: Organise tasks, report issues, and track progress using built-in issue boards.

- Reproducible research: Maintain structured and well-documented code to ensure analyses can be reproduced and verified.

- Automation of workflows (CI/CD): Automatically test, validate, or deploy code when changes are made.
