---
title: ADA HPC
categories: [Tools]
aliases:
  - bazis.html
---

## What is it?

ADA is a high performance compute (HPC) cluster for research at the Vrije Universiteit Amsterdam. ADA is named in honour of [Ada Lovelace](https://en.wikipedia.org/wiki/Ada_Lovelace), the pioneering mathematician and writer known for her work on Charles Babbage's Analytical Engine. She was the first to recognise that the machine had applications beyond pure calculation. ADA is the rebranded name of our previous cluster, BAZIS, and is maintained by the IT for Research team.

ADA is a heterogenious cluster composed of partitions and servers financed by various VU research departments and the VU IT department. The cluster is particularly useful for executing multi-node computations that are not possible on the general VU compute servers but do not require the scale of the National Supercomputer, Snellius.

ADA users are granted access to a set of compute partitions based on the resources owned by their research department. Users not affiliated with a research department that owns cluster hardware can get access to the community partition.

A large collection of tools, compilers and libraries is available for your analysis, and your data on [SciStor](../topics/SciStor.qmd) are directly accessible from ADA.

## What can it be used for?

Most researchers start out by running their analysis tools on their laptop. The performance of a laptop is limited however. You might find your analysis takes up so many resources that your laptop becomes unusable for other tasks, or tasks take so long that you have to find a way to keep your laptop running overnight. For example a lot of AI tasks, such as running Large Language Models (LLMs), require a dedicated GPU, which most laptops don't have. These tasks will run very slowly, or not at all.

A next step might be purchasing a Workstation with more performance and maybe a GPU. You can run the same applications as your laptop and leave it running overnight and during weekends. The modern VU offices are not geared for workstations, however, so that might not be possible.

The point where your laptop or even a workstation becomes unusable for your analysis workflow is when you should consider HPC. HPC nodes have a large amount of RAM, many processor cores and often multiple GPUs. HPC clusters work with a queueing system, meaning the system will wait until enough resources are available to run your job and it will run multiple jobs simultaneously so its resources are used optimally.

Be aware that it is generally not possible to run graphical desktop applications (such as RStudio, SPSS or ArcGIS) on an HPC cluster. Your analysis needs to be able to run as a script that can be started from a Linux command line. This means there is a learning curve to use HPC, especially if you are not used to a Command-line Interface (CLI) and scripting.

CLI and scripting skills are very useful to have for every researcher, but  if you feel you do not have the time to learn these skills there might be other options available such as [the VU Compute Hub](https://hub.compute.vu.nl) or [SURF Research Cloud](../topics/researchcloud.qmd) where you can run some graphical tools.

### GPUs in ADA
Some workloads, such as Machine Learning, require a GPU. At the moment only some of the compute nodes in the ADA community partition have GPUs, the availability is not sufficient for everyone at any given time. If your workload requires more extensive use of GPUs and your department has no dedicated compute nodes with GPUs, you can apply for access to the national HPC infrastructure [Snellius](../topics/snellius.qmd) or consider [buying ADA compute nodes](#buying-dedicated-compute-nodes) with GPUs for your department. 

## How to request access

A form to request an account on ADA can be found on 🔒 [VU Service Portal](https://services.vu.nl/esc) under IT > My work field > Research > HPC Cluster Computing > New ADA HPC Cluster Computing.

## Are there costs involved?

The ADA cluster community nodes are free to use for VU researchers, although resources are limited.

### Buying dedicated compute nodes

If your research projects require heavy usage of HPC you can consider spending part of your research budget to buy compute hardware for your group. Please contact [IT for Research](mailto:itvo.it@vu.nl) for more information on what is possible.

## Getting started

You can find information on how to use ADA on [ada-hpc.readthedocs.io](https://ada-hpc.readthedocs.io).

Also take a look at the [SURF wiki Snellius pages](https://servicedesk.surf.nl/wiki/display/WIKI/Snellius), they contain a lot of information that applies to ADA as well.

SURF organises regular "Introduction to Supercomputing" training sessions, these are free to attend for VU researchers. The course is aimed at using [Snellius](../topics/snellius.qmd), but what you learn is applicable to ADA as well. Please consult the [SURF Agenda](https://www.surf.nl/en/agenda) for dates and registration.

## Contact
Wondering if ADA fits your research needs? Please contact [IT for Research](mailto:itvo.it@vu.nl)
