# What AI is and what it is not

In recent years, Large Language Models (LLMs) have become the most prominent type of AI in the public eye. Their user-friendly chatbot interface has made it easy for anyone to access these models by simply logging in and sending a message. Consequently, there has been a surge in the industry, with many people using LLMs for various purposes. But what exactly are these “AI agents” that everyone is discussing?


# What AI is
The basis of LLMs is a huge database of text data. Companies have scraped the web (legally and illegally-link here) to gather text information on as many topics as they can. Using machine learning, the model will take input text and statistically predict the most likely response word by word or chunk by chunk. With so much data and a focus in the training on forum text and a chatbot angle, the model can provide a written response that seems perfectly appropriate. Most of the models from GPT3 onwards have human-like responses, and this is where industry interest grew, and they all have the signature confidence of the previous generations. This works remarkably well, at least for topics it has seen before (and often enough). 

In broad terms, there are two model categories. The "static" models that are not connected to the internet will provide answers based on what they have in their database, which means you wouldn't get an answer about what today's weather is, or at least not an accurate one. The "live" models can search the internet and scrape an answer, but without proper context, they can still give a wrong answer. The more niche your question, the less information is available in the model and the more likely that it directly paste the information it has or that it will begin to make things up. The model aims to please and will always try to answer.

Almost all machine learning models these days use reinforced learning, and LLMs are no exception. This is the same as giving your dog a treat when it does a trick or listens to a command. You train the dog (or model) with a treat, and after a while, it will repeat the behaviour without the treat. Unfortunately, this can result in repeating the behaviour at inappropriate times to try to get a treat. You might have experienced this with your own pet or seen others struggle with it: a dog repeatedly rolling over, as that always provided a treat in the past. The same can happen with machine learning models. As LLMs are trained and rewarded for generating an answer regardless of truthfulness, LLMs will very convincingly make something up to give an answer, rather than saying ‘I don’t know’. This phenomenon of ‘inventing’ information is commonly known as hallucinations.


# What AI is not
LLMs are not the same as a search engine; you can be less precise in your question than a search engine might like, but the chatbot will not, by default, provide links to sources of its answers. 

LLMs are not a source of truth. LLMs are trained on enormous amounts of data from various data sources, thus ensuring the correctness of an LLM-generated statement is very difficult without the ability to confirm the source of the statement. For things you can check immediately, such as programming, this might not be a big issue, but asking a model to review a large document for you is likely to result in error and that is more difficult to confirm. 

LLMs are not private or secure. All online models you use will take the text and data you provide and feed it back into the model to help improve it, which means anything you give it could, in theory, be retrieved. Exceptions may apply to institutionally-approved platforms where you can log in using your VU credentials, and Nebula (shameless plug)

LLMs are not a storage solution. Despite the ability to upload files, you should not use it as a way to store or transfer files between machines. The companies retain the right to remove these whenever they wish. Companies may also use the contents of the files you upload, which may not be desirable for internal documents or unpublished or confidential research (data).

LLMs are not researchers. You could use them in a research project, but they do not think and therefore cannot assess the quality or validity of data or information fed to them, or the output that they create. This is YOUR responsibility as a researcher.

LLMs are not a source of innovation. By definition, they are a mass of thoughts and ideas that already exist; they spit those out in the same order they went in or sometimes in a new order. To get something entirely fresh from them is not how they work. 

LLMs are not a trustworthy work partner. Their need to answer and please the user means they often lie or will provide little to no pushback on bad ideas, which can result in poor work output.

LLMs are not neutral. The responses they provide reflect biases in the model itself and in the data used to train the model. They may amplify bias that exists in the world more broadly.
