---
title: Data Citation
---

## Citation Elements

Citing data is not different from citing a journal publication. Similar to citing a journal publication, it helps to give and receive credit, and show the impact of the original source.

Make sure to check the rules of the journal to know how you should cite when writing an article for a specific academic journal. For all of the journals, however, the minimum compulsory elements in a data citation include:

* Author(s): Name of the author (creator) of the dataset
* Title: Name of the dataset
* Date of publication
* Publisher: Archive where dataset is stored
* Persistent Identifier: Unique identifier, most common is the DOI (see section [Persistent Identifier](../topics/persistent-identifier.qmd)).

Optional elements that may be included in the reference are:

* File Type: Codebook, movie, software
* Version: Version number of the edition
* Creation Date
* Date of Consultation (last)

If you (re)used another, openly accessible dataset *to create your own*, it is also important to (first check that the original dataset's licence permits this and to) cite that dataset correctly. If you want to make clear in a journal article that another dataset was reused, you can add this information, including a citation to the original dataset, to the data availability statement, besides the reference list. In your own dataset, you can use the [README file](../topics/data-documentation.qmd#readme) to cite the original dataset and explain how it was reused. You should also add documentation about what processing you did to the original dataset to create your own, and refer to this documentation in the README file. Many repositories prescribe a standard way to cite datasets for several citation styles, and one can very often simply copy and paste that. For example, Zenodo has a citation box on the bottom right of the page, and there one can choose a citation style and simply copy that or export the citation to a citation file (which is useful if you are using EndNote or Zotero). The same can be done in Datacite ([example](https://commons.datacite.org/doi.org/10.5281/zenodo.6949511)).

### Example data citation

Stephens, William, 2020, "Resiliences to Radicalisation - QSort Data", [https://doi.org/10.34894/35MTMN](https://doi.org/10.34894/35MTMN), DataverseNL, V1.

---

For more information, see the following guidelines:

* [Dataverse](https://dataverse.org/best-practices/data-citation)
* [DataCite](https://datacite.org/cite-your-data.html)
* [DCC UK](https://www.dcc.ac.uk/resources/briefing-papers/introduction-curation/data-citation-and-linking)
* [Data Citation Synthesis Group (2014). Joint Declaration of Data Citation Principles. Martone M. (ed.) San Diego CA: FORCE11](https://www.force11.org/group/joint-declaration-data-citation-principles-final)
* [CESSDA on accessing, using and citing data](https://dmeg.cessda.eu/Data-Management-Expert-Guide/7.-Discover/Access-use-and-cite-data)
* [CESSDA on citing your own data](https://dmeg.cessda.eu/Data-Management-Expert-Guide/6.-Archive-Publish/Publishing-with-CESSDA-archives/Citing-your-data)

Relevant is also the [Citation File Format (CFF)](../topics/cff.qmd).
