---
title: Data Archiving
categories: [Research Data]
---

## What is data archiving?

When we mention **data archiving** at VU Amsterdam, we mean the following:

> Creation of a secure and immutable copy of research data, associated metadata, accompanying documentation, and software code (where relevant) with the intention to ensure (conditional) access for a predetermined, minimum, period of time.

As stated in the [Research Data and Software Management Policy](../topics/research-data-and-software-management-policy.qmd), researchers are responsible for archiving all research data and software that leads to a published result (either in an article or other narrative form) in a trusted repository for a period of at least ten years after this publication, unless legal requirements, discipline-specific guidelines or contractual arrangements dictate otherwise.

## Purpose

Data archiving is crucial for enabling verification of research data. Verification is important for a transparent research practice, a value VU Amsterdam is strongly committed to. Archiving your data ensures that data will be preserved for the long term and that data can be accessed if necessery, even when the Principal Investigator or other members of the research team are no longer available at VU Amsterdam.

## Requirements

At VU Amsterdam, we strive to make our research data [FAIR](../topics/fair-principles.qmd). When datasets are archived in a repository provided by VU Amsterdam ([Yoda](https://publication.yoda.vu.nl/) or [DataverseNL](https://dataverse.nl/dataverse/vuamsterdam), the following requirements apply:

- the data must be provided with Metadata according to the [VU Minimal metadata guide](https://github.com/vu-rdm-tech/metadata/blob/main/minimal_metadata_guide.md);
- the data and software must have a [Persistent identifier](../topics/persistent-identifier.qmd) (or Identifiers) to increase findability;
- a licence must be applied to the data and software in order to indicate if it can be reused by others and if so, under which conditions.

If you use an external repository, these requirements are useful to keep in mind as well, because they make the data FAIR to a large extent, but in that case you will have to rely on the properties of the repository.

## How does data archiving work in practice?

As mentioned above, data archiving must happen in a repository. This means that data storage solutions for during research, like Research Drive, are not suitable for data archiving. They don't generate a [Persistent Identifier](../topics/persistent-identifier.qmd) and do not ask for metadata or a licence. Detailed workflows addressing archiving data can be found in the guides about [making your data FAIR](../guides/document-and-preserve.qmd) and [archiving and publishing data](../guides/publish-and-share.qmd).
