---
title: Best Practices for Data Storage
categories: [Research Data,Knowledge Items]
---

This page aims to provide you with some practical technical and organizational guidelines on storing research data. In general you should keep in mind that data should be easy to work with for both humans and computers.

## Avoiding technical issues
To to improve resability of your research data and avoid techincal issues it is good to follow some best practices in naming your files and folders. 

:::{.callout-note}
This is meant as a guideline, if your source data does not adhere to these practices it is not always feasible to rename everything. [The VU provided storage platforms](https://rdm.vu.nl/tools.html#category=Data%20Storage) will be able to store it properly, but be aware of the issues mentioned. 
:::

### Only use lowercase characters
Linux and [Yoda](/tools/yoda/index.qmd) are case sensitive, but Windows and MacOS are not, which leads to unexpected behavior when transferring data. For this reason it is best to stick to lowercase characters in file and folder names, especially when creating data on a Linux system such as [ADA](/tools/ada/index.qmd) or [Snellius](/tools/snellius/index.qmd).

### Avoid spaces
Use `-` or `_` instead of spaces, this keeps file and folder names readable without sacrificing technical accessibility. 

Accessing data from the CLI (Command Line Interface) or a script is a lot easier if you avoid spaces. 

Take attempting to view the file `run 1/lab output.txt` with the `cat` command.
```sh
~$ cat run 1/lab output.txt
cat: run: No such file or directory
cat: 1/lab: No such file or directory
cat: output.txt: No such file or directory
```
You must either "escape":
```sh
~$ cat run\ 1/lab\ output.txt
Output from my lab equipment
```
Or use quotes:
```sh
~$ cat "run 1/lab output.txt"
Output from my lab equipment
```
Avoiding spaces, the path is just as clearly readable, but easier to access:
```sh
~$ cat "run1/lab_output.txt"
Output from my lab equipment
```

### Avoid other special characters
Modern filesystems can deal with special characters, such as ``! # $ % & ' " ` @ ^ ~ + , . ; = ) (``, in file and folder names, but applications might have trouble. Special characters, like spaces, also often need to be "escaped" on the commandline. 

### Keep file and folder names as short as possible
Windows for example has a maximum path (folder, subfolders and file) length of 250 characters. You could create a much longer path on a Linux system (such as ADA or Snellius) and find you are unable to download it to a Windows laptop. 

File and foldernames should be short but descriptive. Avoid nesting subfolders to deep. 

## Make a plan
You should certainly make a practical plan on how to work with reseach data when working with collaborators. But even if you are the only one working on the project it is useful to think on a useful data structure and naming scheme.

### Agree on a naming convention before you start a new project
Some topics to decide on:

- Hyphens or underscores?
- Dates in file and folder names? If using dates: YYYYMMDD is unambiguous, short and sorts well.
- Version numbers in file names? Avoid using FINAL, it never is.
- Prefixes for document types? INV for invoices, etc. This will make finding files easier.
- A folder structure. Where you will put which data. 

### Agree on how to work with files
Most tools and storage platforms do not allow you to work on files simultaneously. 

With the exception of tools like Office365, most applications will not allow you to work on files simultaneously. This means the last person who saves a file "wins", overwriting a colleagues edits. In the best case a file is "locked" so only one user at a time can access it. Make sure you communicate who works on what files and when, choosing a good folder structure helps with that.

### Document your choices
Document relevant choices in a README file so collaborators know what to do and future users of the dataset can navigate the dataset more easily.

## Working with your research data on a laptop
Roughly speaking there are 3 ways to make your research data available to analysis tools running on your laptop:

| | SciStor | Research Drive | Yoda |
| --- | --- | --- | --- |
| Access it directly on a mounted drive (driveletter) | ✅ | 〰️ | 〰️ |


### 1. Access it directly on a mounted drive (driveletter)
> Main way of working with SciStor

#### Tips 
- Check all new data you produce is stored on the storage

[SciStor](/tools/scistor/index.qmd) can be mounted as a drive letter, make sure your applications automatically save new files there.

### 2. Manually copying the data to the computer
> Main way of working with Yoda. 

#### Tips
- The [Yoda documentation](/tools/yoda/analysing_data.qmd) has more detailed tips for working with your data.

- Avoid inadvertently syncing the data to cloud storage

Make sure you don't copy or download research data to folders synced to cloud storage (Research Drive, SURFDrive, OneDrive, Google Drive, etc.), especially when working with sensitive data. Only copy the data to synced folders if it really needs to be on the cloud storage.

Especially take note of OneDrive. The "Documents" folder is automatically synced to OneDrive and many applications use it as the default location to store new files. To ensure data does not inadvertently end up on OneDrive check where you save data from for example Office applications.

### 3. Automatically transferring the data using a sync tool
> Main way of working with Research Drive, Surfdrive, Onedrive

#### Tips
- **Check the syncing is still working**

If you do rely on automatically syncing files with for example Research Drive, periodically check the data is indeed present online. You do not want to find out the Sync client has not been working when your hardware fails.

- **Syncing is not the same as a backup!**

Syncing your local data to cloud storage such as Surfdrive, Research Drive or Onedrive is a very useful way to work with data on Cloud Storage. But please note it does not protect you against accidentally deleting or overwriting data unless the Cloud Storage itself is backed up! 

[The VU provided storage platforms](https://rdm.vu.nl/tools.html#category=Data%20Storage) are all backed up.


