---
title: Data Storage
---

## Storage During Research

VU Amsterdam offers several options to store your research data. The choice for a specific option may depend on factors such as:

* Does a project involve multiple organisations or departments?
* The sensitivity of the data: does it involve personal data or copyrighted / commercial data?
* Are there any research partners with whom data need to be shared?
* Are any commercial parties involved?
* Does the research project involve multiple locations (inside or maybe even outside the EU)?
* Will there be (lab) devices producing data that need to be stored as well?
* What will be the volume of the data?
* Will there be lots of interactions with the data (using software/tools)?

Storage options may take several forms, for example:

* Local storage on computers, networks or servers;
* Cloud storage offered by VU Amsterdam;
* Locations where physical data samples are stored (fridges, lockers, etc.).

Researchers, including PhD candidates, have multiple options that can be used, some of which are listed below. More information about these storage options is available behind their respective links. The [Storage finder](https://vu.nl/en/research/storagefinder) is a tool that will give you a number of storage options suitable for your research. For more individual guidance, please get in touch with the [Research Data Management Support Desk](mailto:rdm@vu.nl) for advice, particularly when you are working with commercial, personal or otherwise sensitive data, or when you have a complex IT setup.

## Standard services offered by VU Amsterdam

VU IT offers several services for employees to store their files. Examples are:

* 🔒 **[OneDrive](https://services.vu.nl/esc?id=emp_taxonomy_topic&topic_id=eed3d23e9785d950e553359fe153affc)**: personal storage for all VU employees and part of the Microsoft 365 platform. OneDrive allows you to store files locally and in the Microsoft cloud, and share folders and documents with colleagues. Since this is personal storage, tied to someone's personal VU account, we don't usually recommend storing research data in OneDrive: if the account holder leaves VU Amsterdam, the account and all the data on it, disappear.

* 🔒 **[Teams](https://services.vu.nl/esc?id=emp_taxonomy_topic&topic_id=e7d2b062973e0950e553359fe153afc1)**. Faculties, divisions and departments have their own Team - part of the Microsoft 365 platform - where they store shared documents and where they can interact and chat. Projects may also request a project team. But note that Teams is not always the best location to store your **research** data and has several limitations, especially when it comes to working with non-Microsoft file formats, large volumes of data, interacting with data, and collaborating with partners outside of VU Amsterdam. Contact the [RDM Support Desk](mailto:rdm@vu.nl) to find out more about the suitability of Teams for your project.

## Research data-specific storage options

The options above are standard data storage options at VU Amsterdam to which all employees have access. But VU Amsterdam also offers storage specifically for research data. Some of them are hosted locally at VU Amsterdam, while others are SURF cloud services. When selecting a cloud-based service it is important to remember to check **where** the data will be hosted. If the research project involves sensitive data it may be necessary to choose cloud-based options that guarantee that the data will stay in the EEA or on servers based in the EEA.

* 🔒 **[SciStor](https://services.vu.nl/esc?id=emp_taxonomy_topic&topic_id=86ad5a5f978f09d0e553359fe153afb3)** (short for ‘Storage for Scientists’): This is storage hosted by IT for Research (ITvO) and allows for inexpensive storage of large volumes of data. There are various levels of security possible and various ways to get access to the files. SciStor is only intended for ongoing research, not for archiving.

* **[Yoda](https://yoda.vu.nl/site/index.html)** (short for Your Data) is a cloud storage at SURF and is suitable for storing large-scale and sensitive datasets. Yoda also supports collaborating on projects in and outside VU Amsterdam and adding contextual information ([metadata](../guides/document-and-preserve.html#metadata)) about your dataset as you go. Yoda is *usually* the best choice if your research data are very sensitive.

* 🔒 **[Research Drive](https://services.vu.nl/esc?id=sc_cat_item&sys_id=39d345f097066990e553359fe153af01)** is a cloud storage at SURF for research projects and is suitable for collaboration in and outside VU Amsterdam, for storing sensitive data and large-scale research projects. You are able to request storage space in Research Drive via a 🔒 [web form](https://services.vu.nl/esc?id=sc_cat_item&sys_id=39d345f097066990e553359fe153af01) in the selfservice portal (VU employees only). Research Drive is the best choice if you need to manage access rights on a folder level. [SURF has general information about Research Drive](https://www.surf.nl/en/research-drive-securely-and-easily-store-and-share-research-data), and [you can find tutorials on the wiki pages](https://servicedesk.surf.nl/wiki/display/WIKI/Research+Drive).

There are differences between Research Drive and Yoda and each one may support certain projects better than others. The [storage finder](https://vu.nl/en/research/storagefinder) can help you to get an idea of what would be the best choice for your project, but get in touch with the [RDM Support Desk](mailto:rdm@vu.nl) for more details. Costs for each of these storage options are detailed on the [VU website](https://vu.nl/en/employee/research-data-support/research-archiving-storage-cost-model), including details on how the costs are calculated and billed.

## Sending research data to partners

Some projects may require data sharing with partners. Although Research Drive and Yoda support sharing data all through the project, it may also be the case that some data only need to be sent to a partner once. There are some secure options to send data to research partners:

* 🔒 **[Surf Filesender](https://services.vu.nl/esc?id=emp_taxonomy_topic&topic_id=da7a9e1b978f09d0e553359fe153af98)**: cloud service that allows you to send files of 1 Terabyte to other researchers and encrypted files of up to 250 GB.  

* 🔒 **[Zivver](https://services.vu.nl/esc?id=emp_taxonomy_topic&topic_id=01d4a69797cf09d0e553359fe153afdd)**: All employees of VU Amsterdam can use Zivver, the encryption programme that allows you to send email or data (sensitive or otherwise) securely by email. Attachments will also be encrypted and can be several Terabytes in size (max = 5 TB). Specific information on how to get and use Zivver are available on the selfservice portal. General explanations on how to use it are available at the [Zivver website](https://docs.zivver.com/en/index.html).  
