---
title: Data Management Plan (DMP)
categories: [Research Data]
---

## What is a DMP

A Data Management Plan (DMP) is a document outlining how research data will be handled throughout the research life cycle. A DMP is a structured way to address data collection, organization, storage, sharing, and preservation. It also outlines the measures taken to ensure data security and addresses how data will be preserved and made available for future use.

## DMPonline

VU Amsterdam offers the online tool [DMPonline](https://dmponline.vu.nl/) for writing Data Management Plans. DMPonline is a platform that offers a range of templates, ensuring that researchers can create DMPs to meet the standards of diverse funders and institutions associated with their projects. DMPonline makes it easy to work on a DMP together with colleagues, advisors, or other stakeholders. VU Amsterdam researchers can use the `request feedback` function of DMPonline to get their DMP reviewed by a faculty data steward or RDM Support Desk colleague.

Instructions for selecting the right DMP template in DMPonline are available in the [guide How can you set up research data management from the start?](https://rdm.vu.nl/guides/plan-and-design.html).

If you have questions about DMPonline, or encounter problems when using the tool, please get in touch with [rdm@vu.nl](mailto:rdm@vu.nl).

## What is data

Research data is any information that has been collected, observed, generated or created to validate original research findings. Examples of data could be interview recordings, experiment results, physical measurement, notes from focus group's meetings, notes from fieldwork, observations captured in photographs, film or audio, text files extracted from a corpus, image of archival items or artworks, scraped websites, responses to survey questions.  Algorithms, simulations, code, scripts and software are often also considered as research data. There is also physical data: (biological) samples, collections, artifacts etc.

Administrative documents, like informed consent forms and key files should be acknowledged as important elements of research data as well.  

## Data Assets

At VU Amsterdam, we sometimes use the term 'Data Assets'. You can think of data assets as small 'parcels' of data that can change form or format throughout the research. For example, if you're sending out surveys for your research, the survey responses are considered a data asset. If, in addition to the surveys, you're also holding focus groups, the data collected from the focus group are also considered a data asset, separate from the survey results. Most projects will have more than one data asset per data stage. It is common to provide data assets based on the data stage such as raw, processed, or analysed. Raw Data refers to original data collected, Processed Data is data that has undergone some level of transformation or organisation. Processing involves cleaning, formatting, and structuring raw data to make them more understandable and suitable for analysis. Analysed Data usually results from statistical methods, detailed examination or interpretation.

Here are some examples of data assets in research data management:

| Data Stage     | Dataset description         | Type of data    | Format |
|----------------|-----------------------------|-----------------|--------|
| Raw data       | Interviews                  | Audio files     | MP3    |
|                | Spectographic analysis      | Text files      | CSV    |
| Processed data | Transcription of interviews | Text files      | Docx   |
|                | Data spreadsheet            | SPSS files      | SAV    |
| Analysed data  | Regression graphic          | Graph           | PNG    |
|                | Data table                  | Word file       | Docx   |
| Other          | Poster presentation         | Powerpoint      | PPS    |
|                | Project Website             | HTML            |        |
|                | Analysis code               | Text files      | Python |

Note that these data assets also change in the different phases of the research! While the interview data are audio files in the raw stage, they are transcribed and become text files in the processed stage.

## DMP Elements

VU Amsterdam DMP template consists of seven sections with questions. In DMPonline, there is guidance available for all sections, as well as example answers. When you are writing your DMP, you can consult this information directly in DMPonline. Below we provide  references to information and support available for various RDM-related aspects.

### Legal and ethical requirements

#### Working with personal data

If you have questions about working with personal data in research, please get in touch with the Privacy Champion of your faculty. The 🔒 [overview of Privacy Champions](https://vu.nl/en/employee/privacy-and-information-security/privacy-champions-information) can be found on VU Amsterdam website. Make sure to contact your Privacy Champion in the following situations:

- If you need to carry out a DPIA, or if you're unsure if you need to do one
- If you work with special category personal data, or otherwise very sensitive data
- If you are collaborating with other parties
- If you need software for which no licence is set up on behalf of VU Amsterdam
- If you wish to reuse existing data containing personal data

It is impossible to provide an overview of tasks to be carried out to ensure compliance with the GDPR that fits all research projects. For that reason, it is important to contact your Privacy Champion. They will be able to identify what needs to be arranged to adhere to the GDPR.  

#### Ethical Review

```{.include shift-heading-level-by=4}
../topics/ethical-review.qmd
```

### Storage and backup during the research process

An overview of storage facilities at VU Amsterdam is available in the [Data Storage Finder](https://vu.nl/en/research/storagefinder). You can use this as a starting point to navigate storage solutions.

If you have questions about data storage and backup, send an email to [rdm@vu.nl](mailto:rdm@vu.nl).

### Data archiving and publishing

If your research data contains personal data and you're unsure about which data may be published, please contact your 🔒 [Privacy Champion](https://vu.nl/en/employee/privacy-and-information-security/privacy-champions-information).
