---
title: Data Transportation and Transfer
categories: [Research Data]
aliases:
  - safe-data-transfer.html
---

It is important to protect your data during the entire data life cycle. To find out whether your data are secure during all stages of your research, think about your data flow: where do your data originate and where do they go to? If data need to be transported from one physical place to the other, from one storage platform to another, or  from one device to another, these actions should happen in a secure way.

Even if a formal [Data Management Plan (DMP)](./data-management-plan.qmd) is not strictly required, it is still good practice to have a plan on how to handle your research project's data from start to end. Always ensure you are informed on any [legal and ethical requirements](./data-management-plan.html#legal-and-ethical-requirements) for your research data.

## Transferring digital data

### Data collection on campus

If data collection takes place through a certain measurement device (e.g. MRI scanner, EEG scanner, eye tracker), the data need to be transferred from the measurement device to the storage location that you will use during your research project. The best way to do this is to write the data directly to [SciStor](./scistor.qmd). Please contact [IT for Research](./itvo.qmd) for advice. 

Sometimes it is not possible to write the data directly to a storage platform, for example if there is no way to connect the device to the campus network (e.g. a portable audio or video recording device). Make sure that transfer takes place in a secure way, especially when the data is sensitive, for example by using an encrypted USB drive to transport the data or by copying the data off the device in the lab itself. 

Make a plan for managing data on the measurement device. Make sure a copy and backup are made before deleting data from the device itself.   

### Data collection outside campus (online)
If you are doing fieldwork outside the campus and you have reliable and secure internet access, it is a good idea to upload the data to a storage location that is regularly backed up and secure, in order to prevent data loss. All the VU-supported [storage solutions](./data-storage.qmd) are backed up, some of them also allow access for external collaborators. 

It is always good practice to use [eduVPN Institutional Access](https://vu.eduvpn.nl/) on untrusted (wireless) networks.

### Data collection outside campus (offline)
If you are doing fieldwork in an area with limited internet access, you might use a portable device to initially store your data, such as your laptop, USB drive or SD card. Make sure to keep at least 2 copies of the data (for example your laptop + a USB drive or on 2 USB drives). As soon as you are in a place with an internet connection you can upload the data to a secure [storage space](./data-storage.qmd).

Please make sure that the data on portable devices is secured, by using encryption (and by transporting them safely by using a lockable briefcase or backpack). You can 🔒[request encrypted USB drives from IT]((https://services.vu.nl/esc?id=sc_cat_item&sys_id=73eaf6e147264150bfa46d72e36d43d6)), your VU laptop is always encrypted.

## Transferring large amounts of data
Sometimes you need to transfer a large amount of data (tens of Terabytes and/or millions of files) from one storage platform to another. Such a transfer could take days, making it unfeasible to use your laptop. There are a number of measures you can take to ensure safe and complete transfer of large datasets:

-  Use a file sync tool, such as [rsync](https://linux.die.net/man/1/rsync), [rclone](https://rclone.org/) or [robocopy](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy). This allows you to restart the data transfer if the connection gets interrupted. It also (partly) ensures the dataset is complete.

- Run the transfer on a computer that can stay online 24/7, such as ssh.data.vu.nl or a SciCloud server. 

- If your storage platform and sync tool support calculating checksums you can ensure all files are copied completely. This is especially important if you plan to remove the data from the source location.

Which tools work best is highly dependent on the source and target storage platforms. Contact [IT for Research](./itvo.qmd) for advice, they can also help setup a temporary server for the transfer.

## Transporting physical data

If physical objects need to be transported, you should check with the data manager at your department (if available) what options are available. Special briefcases that can be locked or secure backpacks may need to be used to keep informed consent forms or other sensitive data objects (USB drives etc.) secure during transport. A checklist may help to ensure all objects will be taken along.

## Data transportation and transfer across borders

Some countries have rules to control the movement of encryption technology that enter or exit their borders. If you need to travel with an encrypted laptop to secure your data, for example during fieldwork abroad, please keep this in mind. If you need to transfer data in and out of such countries, please get advice on encryption and secure transportation at the [IT Service Desk](mailto:servicedesk.it@vu.nl).

## Sending data
A storage platform that allows collaboration is the easiest way to share data, but sometimes you might need to send data to a third party as a one-off. Regular email is not suitable for sending sensitive data, but there are alternatives:

- **[Zivver](https://www.zivver.com/products/email-encryption-software)** offers a secure way to send (large) files. You can find information on how to use Zivver in 🔒 [the VU service portal](https://services.vu.nl/esc?id=kb_article&sysparm_article=KB0012157). 

- **[SURFfilesender](https://filesender.surf.nl/?s=home)**  is a web based application that allows authenticated users to securely and easily send arbitrarily large files to other users. Users without an account can be sent a guest upload voucher by an authenticated user. FileSender is developed to the requirements of the higher education and research community.

Please contact the [IT Service Desk](mailto:servicedesk.it@vu.nl) if you need help in using these tools.