---
title: Ethical Review
categories: [Responsible Scholarship]
---

In cases where research involves human or animal participants, a research proposal may need to be reviewed by an ethics committee. VU Amsterdam and Amsterdam UMC (location VUmc), have several ethics committees, which are listed below. Please note that researchers at VU Amsterdam also have to go to the METc at VUmc if their research is [subject to the WMO](https://english.ccmo.nl/investigators/legal-framework-for-medical-scientific-research/your-research-is-it-subject-to-the-wmo-or-not), which is not restricted to research at VUmc.

## Ethics committees

* ACTA: [ACTA Ethics Review Board](https://acta.nl/en/research/more-about/ethics-review-board) (ETC), Academisch Centrum Tandheelkunde Amsterdam
* Beta: [Research ethics review committee Faculty of Science](https://vu.nl/en/about-vu/faculties/faculty-of-science/more-about/research-ethics-review-committee-beta) (BETHCIE), Faculty of Science
* FGB: 🔒 [Scientific and Ethical Review Board](https://vu.nl/en/employee/behavioural-and-movement-sciences-getting-started/the-scientific-and-ethical-review-board-vcwe) (VCWE), Faculty of Behavioural and Movement Sciences
* FSG, Faculty of Social Sciences and Humanities:
    * SGW: [Ethische Toetsingscommissie Onderzoek](https://vu.nl/en/about-vu/faculties/school-of-humanities/more-about/research-ethics-review-committee-and-research-integrity) (EtCO), School of Humanities
    * SSW: 🔒 [Research Ethics Review Committee](https://vu.nl/en/employee/social-sciences-getting-started/research-ethics-review-ssc) (RERC), School of Social Sciences
* RCH: [Ethics Committee](https://vu.nl/en/employee/law-getting-started/ethics-committee), Faculty of Law
* SBE: [Ethical Review Board](https://vu.nl/en/about-vu/faculties/school-of-business-and-economics/more-about/research-office) (ERB), School of Business and Economics
* VUmc (Amsterdam UMC): [Medical Ethical Review Committee](https://metc.amsterdamumc.org/) (METc)
