---
title: iThenticate
categories: [Tools]
---

## What is it?
iThenticate is plagiarism detection software used by researchers to ensure the originality of written work before publication. The approach to plagiarism checks at VU is not primarily for retrospective detection but is rather employed in an educational and preventive manner, explicitly aiming to enhance awareness of scientific integrity in accordance with the Netherlands Code of Conduct for Research Integrity (NGWI).

Starting from September 1, 2022, PhD candidates who commence their studies are required to conduct an initial scan in iThenticate early in their trajectory. The educational aspect involves discussing the results of the scan with their supervisor. The goal is to educate our VU PhD candidates to become engaged and responsible scientific researchers. 

{{< video https://www.youtube.com/watch?v=uMzrnCqA8As&t=6s >}}

## What can it be used for?

Test
iThenticate can be used by PhD candidates to check the originaltiy of written work before publication.

### Data storage
Yoda is a Cloud storage solution that can be used for small to very large datasets. The underlying [iRODS](https://irods.org) software ensures data integrity. Data in Yoda is backed up daily. 

### Data sharing
Once a new Yoda group has been created you can invite collaborators yourself. Researchers from national and international research institutes can login with their institutional account via [SURF Research Access Management (SRAM)](https://www.surf.nl/en/services/surf-research-access-management). Collaborators from non-research institutes can create a free EduID NL account. 

### Sensitive data
The use of Multi-Factor Authentication (MFA) with SRAM and hosting at SURF ensure, among other things, Yoda is suitable for the storage and sharing of data that score High on confidentiality in a data classification (see the [Policy Classification of Research Data](https://rdm.vu.nl/guides/policies-supporting-vision-open-science.html#policy-classification-of-research-data) and the [Research Data Classification Tool](https://vu.nl/en/research/dataclassification)). Please make sure to contact the [RDM Support Desk](rdm@vu.nl) to check if further measures are needed.

### Metadata
At any moment you can add descriptive metadata to a folder in Yoda via a web form. This means you can easily organize your data in such a way that it is not only ready for archiving and publishing but also findable for your collaborators. 

### Archiving
At any moment you can submit a data folder with metadata for Archiving in the Yoda **Vault**. Data in the Vault is read-only and cannot be deleted. To help make sure the dataset is suitable for archiving a Yoda **datamanager** (usually a data manager from your department or a faculty data steward) will review your submission before final approval. Data in the Vault is directly accessible for your collaborators. Access for the Yoda datamanager role ensures the data remains accessible on the long term.

### Publishing metadata and data
From the Yoda Vault you can submit the dataset for **publication**. A [DOI](https://www.doi.org/the-identifier/what-is-a-doi/) will be generated and registered with [DataCite](https://datacite.org/) together with the metadata. DataCite ensures your dataset becomes findable on the internet and citable.

The DOI link will lead to a **landing page** in Yoda showing the metadata. The dataset itself can be Open, allowing direct download, Restricted, meaning other researchers need to follow a data request procedure, or Closed, signalling the dataset is properly archived but not available for reuse. 

### Automated workflows
Since Yoda is build on iRODS you could also build (automated) ingest and analysis workflows using iRODS Rules and Policies. Please [contact IT for Research](mailto:itvo.it@vu.nl) if you need assistance.

## How to request access
Requesting space is done via a 🔒 [request form on ServiceNow](https://services.vu.nl/esc?id=sc_cat_item&sys_id=20436ee397c6a910e553359fe153aff1).Please note that because there can be costs involved (see below) you need to supply a budget code.

Once the project space has been created you can start to invite your collaborators yourself. Note that VU students must 🔒 [connect a token to SURFsecureID](https://services.vu.nl/kb_view.do?sysparm_article=KB0011809) to be able to log in.

### Intake procedure
When you work with sensitive data we will always schedule a meeting with you to help you to safely work with your data.

In the form you can also indicate if you would like some help getting started with Yoda. We can either schedule a short
15 minute meeting to get you started or a longer meeting to have a closer look at your data and help you setting up a workflow.

## Are there costs involved?
The costs of storing data in Yoda are detailed on the 🔒 [VU website](https://vu.nl/en/employee/research-data-support/research-archiving-storage-cost-model). 

## Getting Started
The RDM Handbook has practical [manuals](/manuals/yoda/index.qmd) for users starting with Yoda.

More information can be found on the [SURF User Knowledge base](https://servicedesk.surf.nl/wiki/display/WIKI/Yoda+Hosting).

The [Yoda site of Utrecht University](https://www.uu.nl/en/research/Yoda) also contains useful information and is being redeveloped so it can also be used by VU Amsterdam and the other Consortium Partners.

## Contact
Wondering if Yoda fits your research needs? Please contact the [RDM support desk](mailto:rdm@vu.nl).
