title: iThenticate
categories: [Tools]
---

## What is it?
IThenticate is a plagiarism detection software that compares original work of a researcher with published academic work available online via the internet, and bibliographical databases such as Crossref. The tool scans for text similarity between the original work and published work, resulting in a similarity score. Every similarity found by iThenticate can be analysed, enabling the researcher to look at the specific text and location of the original work

## What can it be used for?
iThenticate is used by researchers to ensure the originality of written work before publication. The approach to plagiarism checks at VU is not primarily for retrospective detection but is rather employed in an educational and preventive manner, explicitly aiming to enhance awareness of scientific integrity in accordance with the Netherlands Code of Conduct for Research Integrity (NGWI).

Starting from September 1, 2022, PhD candidates who commence their studies are required to conduct an initial scan in iThenticate early in their trajectory. The educational aspect involves discussing the results of the scan with their supervisor. The goal is to educate our VU PhD candidates to become engaged and responsible scientific researchers.

## How to request access
Vrije Universiteit Amsterdam has a campus license for PhD candidates only. The key users iThenticate within the faculties are the points of contact for creating accounts for PhD candidates. A list of key users per faculty can be found via the [libguide page ‘contact’] (https://libguides.vu.nl/c.php?g=714180&p=5167373).

## Are there costs involved?
You can find more information on how to use iThenticate on [Libguides] (https://libguides.vu.nl/c.php?g=714180&p=5167370 )

## Getting Started
The RDM Handbook has practical [manuals](/manuals/yoda/index.qmd) on the use of the Yoda for users starting with Yoda.

More information can be found on the [SURF User Knowledge base](https://servicedesk.surf.nl/wiki/display/WIKI/Yoda+Hosting).

The [Yoda site of Utrecht University](https://www.uu.nl/en/research/Yoda) also contains useful information and is being redeveloped so it can also be used by VU Amsterdam and the other Consortium Partners.

## Contact
For support with technical issues related to the software please contact the [RDM support desk] ().
