---
title: IT for Research (ITvO)
categories: [Trainings and Knowledge Items]
---

ITvO (IT voor Onderzoek, IT for Research) is a dedicated team within the university IT department, focused on supporting researchers with IT solutions. We bridge the gap between research needs and IT possibilities, making sure researchers have access to the right tools, infrastructure, and expertise.

## Our Services
- [SciStor](../topics/scistor.qmd): Scientific storage service of VU Amsterdam. Data is stored on campus in our Data Centre.
- [SciCloud](../topics/scicloud.qmd): A flexible platform where researchers can create and manage virtual machines for diverse projects.
- [Ada HPC](../topics/ada.qmd): High Performance Computing cluster of VU Amsterdam, for compute-intensive research tasks.
<!-- TODO - Research Engineering -->

## Consultancy
Does your research project require specific IT infrastructure? Do you need to set up a publicly accessible web application for your project? Is your laptop getting too slow to run your analysis? Does your lab instrument require specialised server software?   

Research projects often have specific IT needs that fall outside the standard solutions the IT department supplies, and they can only be met by expensive custom solutions falling outside your project budget.

IT for Research was specifically tasked to offer researchers _practical_ advice and solutions to make the most of your limited time and budget. We offer:

- **Needs Assessment**: Collaborating with you to understand your research goals and IT requirements.
- **Solution Matching**: Identifying the most suitable university and external IT resources for your project.
- **Technical Support**: Assisting with setup, optimisation, and troubleshooting of research IT environments.
- **Best Practices**: Advising on data management, security and analysis workflows.

## Contact
You can contact IT for Research by using the form on 🔒[ServiceNow](https://services.vu.nl/esc?id=sc_cat_item&sys_id=4e079166978d5950e553359fe153afc5), select "Research" under "Service Domain" or email us directly at [itvo.it@vu.nl](mailto:itvo.it@vu.nl)