---
title: Knowledge Security
---

## Introduction

Knowledge security is about secure international collaboration, which is very important for VU Amsterdam. For international collaboration to take place securely, it is necessary to assess the knowledge security risks associated with the research topic, the data that will be collected and/or the potential collaborative partner(s), which can be an institution or individual(s). This assessment has to take place before and during the start of a new research project. VU Amsterdam developed the Knowledge Security Framework (hereinafter: the Framework) as a useful and mandatory guide on asking the important and critical questions about the background of the foreign partner organisation or person, and the research project itself (topic, data, funding). The Framework and all necessary information regarding knowledge security can be found on the [knowledge security page for employees](https://vu.nl/en/employee/onderwijs-en-onderzoeksbeleid/knowledge-security-for-vu-amsterdam-employees). 

## The importance of knowledge security regarding research data

At VU Amsterdam, we attach great value to international collaboration, which is crucial for top-level research and high-quality academic education. As well as opportunities – for research, education, innovation and open knowledge sharing – it also entails risks. Universities are being targeted for acquiring sensitive knowledge and technologies. A possible consequence of this is the undermining of academic freedom and censorship (including self-censorship). 

The Framework addresses potential ethical issues, such as the risk of violating human rights or academic values, the misuse of knowledge, the safety of researchers and respondents (for instance if the research might cause them to be pressured or coerced), unintended knowledge transfer, and harm to people, animals or the environment. This means that it is important to consider the possible consequences for yourself, your colleagues and the research subjects if your research data falls into the wrong hands, e.g. data on a minority group or a key technology (especially technology that falls under dual use[^1] regulation) that a repressive government can misuse. If you work with sensitive research data*, want to openly publish your data and/or your collaborative partner is an organisation or affiliated to an organisation from a country that has a score of 0.4 or less on the [Academic Freedom Index](https://academic-freedom-index.net/), the collaboration should be discussed with the faculty’s contact person. 

Also, measures can be taken in consultation with the contact person (see [Support within your faculty](#support-within-your-faculty)) and data steward to mitigate the risks. Possible measures include limiting access to sensitive research data (physically and digitally, e.g. encryption), data anonymisation or pseudonymisation, an adequate [data classification](./data-classification.qmd), a Data Protection Impact Assessement ([DPIA](https://rdm.vu.nl/guides/comply-with-gdpr.html#complete-a-data-protection-impact-assessment-dpia)), limiting or excluding collaboration with certain partners and other appropriate protection measures.

\* Sensitive research data regarding knowledge security includes: 
<!-- markdownlint-disable MD033 -->

* Research data that falls under the dual use regulation<sup><a href="#fn1">1</a></sup>; 
* Research data on [key technologies or other technologies that are considered by the Dutch government to be militarily, economically and geopolitically strategic](https://www.nwo.nl/en/key-enabling-technologies); 
* Research data on ethically sensitive topics (see question 5 of the Framework); 
* Research data related to minority or repressed research subjects. 

## Support within your faculty

To provide support regarding knowledge security at VU Amsterdam, each faculty has one or more contact persons available who are the first point of contact for questions regarding knowledge security. The contact persons can be found on the [knowledge security page for employees](https://vu.nl/en/employee/onderwijs-en-onderzoeksbeleid/knowledge-security-for-vu-amsterdam-employees). 

[^1]: Dual use items are defined as 'items, including software and technology, which can be used for both civil and military purposes, and includes items which can be used for the design, development, production or use of nuclear, chemical or biological weapons or their means of delivery, including all items which can be used for both non-explosive uses and assisting in any way in the manufacture of nuclear weapons or other nuclear explosive devices' (definition taken from the European Union's [Dual Use Regulation](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32021R0821)).

