---
title: Open Science
---

[UNESCO defines Open Science](https://www.unesco.org/en/open-science/about?hub=686) as

> a set of principles and practices that aim to make scientific research from all fields accessible to everyone for the benefits of scientists and society as a whole. Open science is about making sure not only that scientific knowledge is accessible but also that the production of that knowledge itself is inclusive, equitable and sustainable

This includes making openly available research data, methods, and documentation where possible. As such, the practices outlined in the {{< var title >}} are a precondition of Open Science.

More information about how researchers can practice Open Science at VU Amsterdam is available on the VU page about [Open Science](https://vu.nl/en/about-vu/organisations/open-science). The VU Open Access Policy and more information about different ways of open access publishing and how VU Amsterdam supports those, can be found on the [VU Open Access page](https://vu.nl/en/employee/open-access).

You can read more about Open Science in the Netherlands on the website of the [Nationaal Programma Open Science](https://www.openscience.nl/en). If you are interested in learning more about Open Science or if you are looking for ways to make your research more open and transparent, you can join the [Open Science Community Amsterdam](https://osc-international.com/osc-amsterdam/), the community of VU employees and students interested in Open Science (joint with the University of Amsterdam and Amsterdam University of Applied Sciences).
