---
title: ORCID
categories: [Research Data, Responsible Scholarship]
---

[ORCID](https://orcid.org/) stands for *O*pen *R*esearcher and *C*ontributer *ID*: A persistent digital identifier for anyone working in academia.
ORCID is a unique personal number that allows researchers to easily and automatically connect and update their research information across a wide range of online databases. 
You can think of ORCID as the academic equivalent of your passport: It ensures other research systems and services know who you are and what you have done. 
You might also think of it as an [persistent identifier](/topics/persistent-identifier.qmd) for people, instead of data. ORCID is the industry standard for funders, publishers, universities and institutions in researcher profiles.

##The advantages of ORCID

• ORCID prevents name confusions and increases visibility
• ORCID is an international standard required for submissions and research proposals
• ORCID saves time by connecting and updating selected repositories
• ORCID is an open, non-profit organization, driven by the scientific community.
• ORCID completely owned by the researcher and useable at all institutions

##automate your visibility

You can easily connect your ORCID to the VU Research Portal and various online platforms such as Scopus, Web of Science, PubMed and CrossRef. 
It ensures that information regarding your publications, affiliations and funding will update automatically across all these platforms and your output getting indexed by Google Scholar. 
ORCID also integrates with most commonly used research information systems, allowing you to easily transfer your research profile to a new employer.

##Setting up your ORCID

The best way to set up your ORCID is directly through the VU Research Portal. 
This ensures that your current affiliation and previous output are automatically added to your ORCID profile and that in the future new information from your ORCID is automatically added to your VU research profile.

If you are an external researcher or research support professional you can set up your ORCID directly on their website by following [this link](https://orcid.org/).

To fully benefit from ORCID, it is essential that your ORCID registration is publicly visible and connected to the VU Research Portal (also known as PURE). 
Following the link below shows you how to create a new ORCID and to connect it to the VU Research Portal. If you already have an ORCID, you can follow this link as well to read how to connect your existing ORCID to the VU Research Portal.

[Set up your ORCID account by following these steps](https://libguides.vu.nl/manage-pure-profile/orcid)

