---
title: Open Science Framework (OSF)
categories: [Tools]
---

## What is it?

The [Open Science Framework](https://osf.io/) (OSF) is a cloud-based open-source research project management tool that supports researchers throughout the active research stage. It facilitates collaboration, connects services across the research life cycle, materials, and other research objects for private use or public sharing. The OSF is developed by the [Center of Open Science (COS)](http://cos.io/) that strives to increase openness, integrity, and reproducibility of research. This is in line with the [VU open science commitment](https://vu.nl/en/about-vu/organisations/open-science) where the aim is to make the process of creating and sharing scientific knowledge more transparent, inclusive and equitable.

* As a **collaboration tool**, OSF helps research teams work on projects privately or make them publicly accessible for broad dissemination.
* As a **workflow system**, OSF enables connections to the many products researchers already use, streamlining their process and increasing efficiency.
* Researchers can manage files, data, code, and protocols in one centralised location and easily build custom organisation for their unique needs.
* Integrated metadata support on project level improves findability and reuse of research materials. Soon content on OSF will support FAIR metadata for all files, which will even further enhance responsible preservation and discovery.

Read more about OSF best practices for new OSF users in [OSF Getting started](#getting-started) below.

## What can it be used for?

OSF can be used during the active research stage. It can be used for preregistration, projects or preprints:

1.  [Preregistration of your research ideas - OSF Support](https://help.osf.io/article/145-preregistration).

2.  Projects: See the [video Welcome to OSF Projects - OSF Support](https://help.osf.io/article/353-welcome-to-projects).

    Whitin an OSF project you can store, share and collaborate with your colleagues. You can invite both internal and external collaborators to different components within your project. You can choose to have your project open, for everyone to read, or you can choose to have it closed for up to four years of embargo. It is possible to create a DOI for your research project, see the manual [Create DOIs (OSF Projects) - OSF Support](https://help.osf.io/article/220-create-dois).

3.  Preprints: OSF can also be used to publish your preprints. See the manual [Creating a Preprint - OSF Support](https://help.osf.io/article/399-creating-a-preprint), which describes in seven steps how you can publish a preprint. Please note that you have to submit it to a [community preprint service](https://help.osf.io/article/686-preprint-services). You can select a preprint service that matches best with your discipline. When your preprint is approved, it will be linked to VU Amsterdam and listed in the [VU preprint overview on OSF](https://osf.io/institutions/vua?resourceType=Preprint).

## How to request access?

If you like to start with OSF please go to: [OSF](https://osf.io/).

You can either create a new OSF account and choose \"Sign up using Institution\" and select Vrije Universiteit Amsterdam [(OSF Guide)](https://help.osf.io/article/271-create-an-osf-account). VU researchers can make use of OSF by logging in with their VUnetID credentials (SSO). The OSF account will be automatically created. Or you can add your VUnetID login to your existing OSF account [(OSF Guide)](https://help.osf.io/article/238-add-a-new-email-address-to-your-account). If you already have an OSF account and would like to affiliate this to
VU Amsterdam, please visit: [Affiliate an OSF Project with an Institution - OSF Support](https://help.osf.io/article/192-affiliate-an-osf-project-with-an-institution) and registrations with the VU ([OSF Guide](https://help.osf.io/hc/en-us/articles/360019738394-Affiliate-a-Registration-with-an-Institution)).

When the OSF account is created, you can start directly with using OSF to create a project, registering your preregistration or publishing using the preprints options at OSF (see the section [What it can be used for?](#what-can-it-be-used-for)).

### Access for students

Students are also welcome to use OSF. Note that logging in with VUnetID requires MFA via de SURFsecureID (with the tiqr app or a YubiKey). [Secure sign on - MS Authenticator activation for SURF Secure ID](https://services.vu.nl/esc?id=kb_article&table=kb_knowledge&sys_id=648865b4874bc15010be65b40cbb3592&recordUrl=%2Fkb_view.do%3Fsys_kb_id%3D648865b4874bc15010be65b40cbb3592) has more information on how to register for MFA if you have not already done so.

## Are there costs involved?

The costs for storing data in OSF are detailed on the [VU website](https://vu.nl/en/employee/research-data-support/research-archiving-storage-cost-model).

OSF storage has a limit of 5GB for a private project and 50GB for a public project. Note that it is possible to request additional (paid) OSF storage via the [Request form](https://docs.google.com/forms/d/1CImattWD9KdefK-vFmMbB1I0pfl4FkKj0e1fNgz0AG4/viewform?edit_requested=true). More information on available storage tiers can be found on the [Supporting OSF Usage page](https://www.cos.io/osf-usage). Another way to acquire more storage is connecting an alternative storage provider via Add-ons as described in [Connecting storage and apps](https://rdm.vu.nl/guides/use-osf.html#connecting-storage-and-apps). The [OSF storage caps page](https://help.osf.io/hc/en-us/articles/360054528874-OSF-Storage-Caps) has more information on extending storage capacity.

## Getting started

To get started with OSF please visit the [Getting started on the OSF (Video) - OSF Support](https://help.osf.io/article/342-getting-started-on-the-osf). You can also subscribe to the onboarding webinars [OSF \| Trainings and Webinars](https://www.cos.io/osf-onboarding?utm_source=osf_onboarding&utm_medium=email&utm_campaign=welcome).

Once a year, there will be an OSF workshop organised by VU application managers, where you learn how you can use OSF. See the [Trainings page](https://rdm.vu.nl/topics/trainings.html#open-science-framework-osf-workshop) for training materials and scheduled workshops. 

More in-depth information is available in the guide [How can you use Open Science Framework (OSF) in your research project?](../guides/use-osf.qmd). See the [Information for new users guide](https://rdm.vu.nl/guides/use-osf.html#osf-information-for-new-users) in that guide for more information for new users.

## Contact - Support options for VU researchers

The following hierarchy of support options is available if you run into problems or have questions about using the OSF.

1.  Try the [OSF Guides](https://help.osf.io/) first, they are quite extensive. Quick start up guide for VU OSF users is available in the section [Getting started](#getting-started).

2.  If the answer to your question is not in the OSF Guides or if you run into a technical problem, you can contact OSF support directly via [the contact form](https://help.osf.io/hc/en-us/requests/new). As a member of OSF institutions, VU users receive priority support.

3.  Contact the application managers through [Contact Research Data Support - VU Service Portal](https://services.vu.nl/esc?id=sc_cat_item&sys_id=c84148af47992510bfa46d72e36d4396) (category; RDM tools and subcategory: OSF) if you have questions with regard to the operation of VU OSF or more general questions about Research Data Management.
