---
title: Pure (VU Amsterdam's Current Research Information System)
categories: [Tools]
---

## What is it?

Pure is VU Amsterdam's Current Research Information System (CRIS) that serves as the central research information system for recording all research activities and outputs. All VU researchers can register their research activities and outputs in [VU Pure](https://research.vu.nl/admin/). This information is used for annual reports and research evaluations. Additionally this information is shown on the publicly available [VU Research Portal](https://research.vu.nl) to increase the visibility and discoverability.

## What can it be used for?

### Research output registration

The following record types can be registered in Pure:

- Publications: This can be (journal) articles, books, conference contributions, working papers, preprints, PhD theses[^1], patents, case notes and web publications.
- Activities: peer review, editorial work, participating in or organising an event, lectures, presentations, consultancy, PhD examinations, visiting external institutions, hosting external visitors and memberships of institutions based on academic expertise.
- Datasets: Research data that you have created for your research also constitutes research output and can be related to publications, projects and software.
- Software: Research software that you have created for your research also constitutes research output and can be related to publications, projects and datasets.
- Prizes/Grants: This can be a prize given for research output or a grant awarded for research proposals. 
- Press/Media: This can be the participations in various media forms as an expert or public engagement activities to promote (future) research.
- Projects: This can be all forms of projects in scope and size[^2] with the ability to link all related research activities and output. 
- Courses[^3]: This can be the development of courses or the presentation of these courses.

[^1]: VU-related PhD theses are registered in Hora Finita and when approved are automatically imported into Pure.
[^2]: Projects registered in the VU financial systems are automatically imported into Pure.
[^3]: All the current courses are automatically imported into Pure.

### Researcher profiles
VU Researchers can create and maintain comprehensive academic profiles by providing personal information, academic background and research focus and interests.

### Reporting
Pure can be used to report on all the content registered. Pure is used for the annual report and research evaluations.  

### CV generation: 
Pure contains a tool to combine all the research activities and personal information into private or public CV documents.

## How to request access

Access to Pure is automatically provided to all VU Amsterdam researchers and PhD candidates[^4].

[^4]: Certain VU functions can have a research component to their workload, but if this is not a standard requirement, a Pure account is not automatically created. Department heads can [request]( https://services.vu.nl/esc?id=sc_cat_item&sys_id=b000b90f478aa110bfa46d72e36d4303) a Pure account and profile to be created for specific VU employees who create research output. 

## Are there costs involved?

No, there are no additional costs for VU Amsterdam researchers to use Pure.

## Getting started

### Accessing Pure

To work within Pure go to [the login page](https://research.vu.nl/admin/workspace.xhtml). You can log in using your VUnetID and password.

### Manage your personal profile

There is a manual available on how to manage your personal profile in Pure: [LibGuides - Personal Profile](https://libguides.vu.nl/manage-pure-profile) 
You can also [link your ORCID profile to your PURE profile](https://libguides.vu.nl/orcid/register), which has as a benefit that publications registered in PURE are automatically added to your ORCID profile.

### Adding research outputs

There is a manual available on how to register different types of research output: [LibGuides - Publications](https://libguides.vu.nl/pure-managing-publications)

There are also other related topics available in the {{< var title >}}:

- [Dataset registration in Pure](../topics/data-registration.qmd)
- [Software registration in Pure](../topics/software-registration.qmd)

Note that the [Research Data and Software Management Policy](../topics/research-data-and-software-management-policy.qmd) states that archived and published data and software must be registered. This is not done automatically. Researchers are requested to check their registrations and evaluate if they are complete. If they have archived or published data or software that has not been included in their Pure profile, they need to add these registrations themselves, as explained in the manual mentioned above.

## Support

Below, you can find the support services for Pure provided by the University Library.

### Training and technical support
The VU Library’s Pure support team provides training and demonstrations on [request](https://services.vu.nl/esc?id=sc_cat_item&sys_id=59e89aab9746a910e553359fe153af1e).

For questions or personal support contact the VU Library's [Pure support team](https://services.vu.nl/esc?id=sc_cat_item&sys_id=b000b90f478aa110bfa46d72e36d4303). 

### Policy and compliance questions
Contact your own department secretariat to learn about required research activity registration besides publications, datasets and software. 
