---
title: RDM Support Desk
categories: [Trainings and Knowledge Items]
---

::: {.callout-tip}
Contact the RDM Support Desk at [rdm@vu.nl](mailto:rdm@vu.nl) or 020 598 53 67.
:::

## What is the RDM Support Desk?

The RDM Support Desk is VU Amsterdam's central helpdesk for researchers for all questions, issues and tasks related to Research Data Management, Research Software Management, and, increasingly, Open Science, from all faculties. The Support Desk also helps support staff colleagues from faculties and other VU divisions, such as IT and the Administrations Office (Bestuurszaken).

Behind the Support Desk are four RDM experts from the University Library, who monitor the questions from Monday-Friday 09:00-17:00. They use a ticketing system to respond to questions. In many cases, you will receive a reply from these experts, but your question may also be forwarded to a colleague in a faculty or a different division. The RDM Support Desk experts are in close contact with data stewards from faculties and their colleagues in the IT for Research team, and they share knowledge and expertise with each other. 

## What does the RDM Support Desk do?

In short, support researchers. This could be related to questions researchers have, for example about data storage, publishing, or the use of RDM tools. The RDM Support Desk also supports researchers with writing a [Data Management Plan](/topics/data-management-plan.qmd) and other RDM-related tasks. There is a second line of RDM application managers (see for example [Yoda](/topics/yoda.qmd) and [Research Drive](/topics/researchdrive.qmd)) who can onboard users and help them with the use of RDM tools. It can also be helpful to contact the RDM Support Desk when you are writing a grant application, and you have to write the [data management section](/topics/data-management-section).

The Support Desk strives to send you a reply within 2 working days. Depending on the complexity of your question, this reply could also be an explanation of how the question will be tackled, or could ask clarifying questions to understand the issue better.

## How can you reach the RDM Support Desk?

You can reach the Support Desk [by email](mailto:rdm@vu.nl) or by phone: 020 598 53 67. You can also request a live or online appointment with one of the colleagues behind the RDM Support Desk.
