---
title: Research Data Management Costs
categories: [Research Data]
---

Many research funders encourage applicants to include data management and sharing costs in research proposals. Some funders will provide advice on costs related to data management. Some remarks on costs are provided here:

* [The Data Management Plan](/topics/data-management-plan.qmd) should describe the activities that incur costs and provide justification for the allocation of resources (example: acquisition of a programmer who will write software needed to capture the data).
* No expenditure can be 'double funded', i.e. a service that is centrally supported by indirect costs must not be included as a direct cost as well (example: computers that are already provided to employees and paid for by the university may not be included).
* The budget and justification should broadly indicate where RDM costs will be incurred, where possible. E.g. data capture and cleaning, data curation and preservation, data sharing.
* Include budget for long-term storage if data are expected to be deposited in a repository not funded by the university or external funders (VU repositories are: DataverseNL, Yoda). 🔒 [VU has an internal breakdown of costs for storage and archiving for VU-managed storage and repositories](https://vu.nl/en/employee/research-data-support/research-archiving-storage-cost-model).

A practical costing tool is available from the [UK Data Archive](https://www.ukdataservice.ac.uk/manage-data/plan/costing). Based on this costing tool, Utrecht University has developed a [guide to calculate the costs of data management](https://www.uu.nl/en/research/research-data-management/guides/costs-of-data-management).
You can use those guides as well to estimate the costs needed specifically for RDM.

Most material costs of the storage solutions offered by VU Amsterdam are covered centrally (up to 500 GB), but if you need to specify the costs for your project, look at the 🔒 [Research & Archiving Storage Cost Model](https://vu.nl/en/employee/research-data-support/research-archiving-storage-cost-model)

Examples to include in a Data Management Plan:

| Data Stage     | Dataset                     | Type of data    | Costs                                                             |
|----------------|-----------------------------|-----------------|-------------------------------------------------------------------|
| Raw data       | Interviews                  | Audio files     | Audio equipment rental                                            |
|                |                             |                 | Location rental costs                                             |
|                |                             |                 | Data storage &amp; backup                                         |
| Processed data | Transcription of interviews | Word files      | Personnel costs: hiring research assistants for manual entry      |
|                |                             |                 | Data storage &amp; backup                                         |
|                | Analysis software           | R script        | Personnel costs: programmer to write a program to mine the data |
| Analysed data  | Regression graphic          | Photoshop files | Software costs                                                    |
|                | Project Website             | HTML, Java      | Hosting fee                                                       |
|                |                             |                 | Personnel to build initial website                                |
