---
title: Research Data and Software Management Policy
categories: [Research Data, Research Software, Policies and Legislation]
---
VU Amsterdam considers the careful handling of research data and software to be very important. The university has therefore formulated a Research Data and Software Management Policy which articulates how to handle research data and software. The policy lists the responsibilities regarding research data and software management for researchers, department heads, faculty boards and the university as a whole.

* VU Research Data and Software Management Policy (2024) in [English](../public/policies-regulations/RDSM-policy-VU-EN-v3.0.pdf) and in [Dutch](../public/policies-regulations/RDSM-policy-VU-NL-v3.0.pdf)

Since the VU Amsterdam policy for Research Data and Software Management is formulated in general terms, faculties have worked out more detailed policies and guidelines for their own faculty. These faculty-specific guidelines can be found below.

* [ACTA RDM policy](../public/policies-regulations/ACTA-RDM-policy-2020.pdf), Academisch Centrum Tandheelkunde Amsterdam (2020, in Dutch)
* [Beta RDM policy](../public/policies-regulations/BETA-RDM-policy-2022.pdf), Faculty of Science (2022)
* [FGB RDM policy](https://fgb-rdm.nl/Policies/FGB_RDM_Policy.html), Faculty of Behavioural and Movement Sciences (2023)
* Faculty of Social Sciences and Humanities (FSG):
    * [School of Humanities RDM policy](../public/policies-regulations/FGW-RDM-policy-2023.pdf) , Faculty of Humanities (2023)
    * [School of Religion and Theology RDM policy](../public/policies-regulations/FRT-RDM-policy-2024.pdf), Faculty of Religion and Theology (2024)
    * [School of Social Sciences RDM policy](https://vu.nl/en/employee/social-sciences-getting-started/ssc-guidelines-for-data-management), Faculty of Social Sciences (2023)
* [RCH RDM policy](../public/policies-regulations/RCH-RDM-policy-2021.pdf), Faculty of Law (2021)
* [SBE RDM policy](../public/policies-regulations/SBE-RDM-policy-2023.pdf), School of Business and Economics (2023)

For RDM policies and guidelines at Amsterdam UMC, location VUmc, please get in touch with [Research Data Management Support](https://www.amsterdamumc.org/en/research/support/services-facilities/data-management/contact.htm) at Amsterdam UMC.

If you have questions about the VU-central Research Data and Software Management Policy, please contact the [RDM Support Desk](mailto:rdm@vu.nl).
