---
title: SURF Research Cloud
---

## What is it?

[SURF Research Cloud](https://www.surf.nl/en/services/surf-research-cloud) is a portal where you easily build a virtual research environment. You can use preconfigured workspaces and datasets or add them yourself. Institutions, research communities and suppliers can contribute to Research Cloud's functionality and catalogue by integrating their computing and data services.

SURF Research Cloud is hosted at the SURF datacenter in Amsterdam.

## What can it be used for?

SURF Research Cloud enables you to run 1 or more servers with applications that can be accessible over the internet.

- Hosting web applications, these can be connected to SRAM for secure authentication. You can easily start more servers to increase availability and preformance.

- Running a desktop environment with analysis tools, use your favorite desktop tools on an environment with more performance. Unlike SciCloud GPU resources are available. You can easily connect an environment to your data on Research Drive or Yoda.

- Hosting a highly secure research environment where sensitive data cannot leave the VRE: [SURF SANE](https://www.surf.nl/en/themes/research-infrastructure/sane-secure-environment-for-analysing-sensitive-data).

## Are there costs involved?

You will need to apply for a wallet with credits, see [How to request access](#how-to-request-access) below.

In 2025 the credit cost is:

- 1.03 credits per CPU hour (only if the system is active).
- 21 credits per GPU hour (only if the system is active).
- HDD storage 681 credits per TB per month, SSD storage 1525 credits per TB per month.

See the [SURF services and rates document](https://www.surf.nl/files/2024-08/surf-services-and-rates-2025_0.pdf).

## How to request access

All VU researchers can get access to SURF Research Cloud. To start building an environment in Research Cloud you need 2 things:

### 1. An SRAM Collaboration connected to Research Cloud

- First apply for a new SRAM Collaboration (CO): log in to [SRAM](https://sram.surf.nl) and click the "Request collaboration" button.
- The SRAM admins at IT for Research (ITvO) will contact you to discuss your specific needs and help you to get started.
- Once the Collaboration request is approved you can connect the Research Cloud Application to the new collaboration.
- Invite the colleagues that need to work in your VRE to your new CO.

### 2. A Wallet with credits

There are 2 ways to obtain credits:

- Apply for a _NWO Small Compute Grant_ by following the links on [the Small Compute applications page](https://www.surf.nl/en/small-compute-applications-nwo). In the request form select "SURF Research Cloud - HPC Cloud".
- If for whatever reason your application for this grant is denied, you could also claim credits from VU Amsterdam [Research Capacity Computing Service contract with SURF](https://www.surf.nl/research-capacity-computing-service-rccs-directe-toegang-tot-onze-rekensystemen-en-expertise) contract. Please contact [IT for Research](mailto:itvo.it@vu.nl) for details on how to obtain these credits.

Once the request is granted you will have access to a _wallet_ in Research Cloud and can start to build an environment.

## Getting started

Documentation for Research Cloud can be found on the [SURF User Knowledge Base](https://servicedesk.surf.nl/wiki/display/WIKI/SURF+Research+Cloud).

[IT for Research](mailto:itvo.it@vu.nl) can assist you in setting up a new Research Cloud environment.

## Contact

Wondering if SURF Research Cloud fits your research needs? Please contact [IT for Research](mailto:itvo.it@vu.nl)
