---
title: SciCloud
categories: [Tools]
---
## What is it?
IT for Research (ITvO) offers SciCloud, a service where server capacity can be purchased to support research applications. SciCloud virtual servers are easy to implement, easy to scale up and down and have competitive pricing based on agreed purchase. The virtual server can be placed in an external network, so services running on it can be made internet accessible. It can also run on an internal network for extra security and access to some VU services.

SciCloud is based on the open source middleware [OpenNebula (ONE)](https://opennebula.io/) and offers a service that allows users to quickly start with a virtual server based on available templates, or to upload one of their own virtual images. This concept is known as Infrastructure as a Service (IaaS).

## What can it be used for?
In principle you can run any software you want on a SciCloud server. Linux OS is preferred, but a Windows server is also a possibility.

Typical use cases are:

- Running web applications and services that need to be publicly accessible 24/7, for example a website showcasing your research, a wiki, chatbot, etc.

- Hosting a licensed server application for your research group, such as software for analysis, software needed to run lab equipment or elab journal software.

- The Virtual Server can also be connected to [SciStor](./scistor.qmd) for environments that need fast access to large amounts of data. 

Note that the SciCloud environment has no GPU, so it is not suitable for running graphical environments and machine learning. 

## How to request access
Via a form on 🔒[ServiceNow](https://services.vu.nl/esc), go to: IT > My work field > Research > SciCloud > Order SciCloud capacity

After you have requested a SciCloud virtual server, IT for Research will schedule an interview to discuss your wishes. 

## Are there costs involved?
Configurations of a virtual server are based on standard "Building Blocks", combinations of the following two options can be purchased: 

• Building Block 1: 1 CPU core with 2 GB RAM 

• Building Block 2: 1 CPU core with 4 GB RAM 

Costs are calculated as: €1 per CPU per month, €1 per GB memory per month, €0.40 per GB storage per year (minimum 20GB)

## Getting started
The IT for Research Team will set up the server(s) with the OS of your choice (Windows or Linux) and will set up a root account for you:

- For access to a Linux server you will need to provide a personal SSH key protected with a passphrase. You will be able to access SSH from home. 

- For access to Windows servers use Remote Desktop Protocol (RDP), only via 🔒[eduVPN institute access](https://vu.eduvpn.nl).

Root access to the server allows you to install all the software you need. Note that IT for Research can help you getting started and will automatically install OS security updates, but you are responsible for installing and maintaining software yourself.

It is possible to take _snapshots_ or _clones_ of the virtual server yourself. This allows you to go back to a previously created configuration, if necessary. In addition, ITvO makes daily backups with which a virtual machine can be restored for up to 30 days on request. 

## Contact
Wondering if SciCloud fits your research needs? Please contact [IT for Research](mailto:itvo.it@vu.nl)
