---
title: Transcription Services
categories: [Research Data]
---

For transcribing audio and video files, researchers at Vrije Universiteit Amsterdam can use the services of [Transcript Online](https://transcriptonline.nl/) and [Amberscript](https://www.amberscript.com/en/).

## Processing of personal data

Conversion of speech to text (transcription) of audio or video files always involves the processing of personal data. For this reason, one cannot hire third parties to transcribe research data without contractual agreements. Both parties, [Transcript Online](https://transcriptonline.nl/) and [Amberscript](https://www.amberscript.com/en/), have signed a blanket [processing agreement](https://rdm.vu.nl/guides/comply-with-gdpr.html#agreements) with Vrije Universiteit Amsterdam, which means researchers do not have to draw up individual processing agreements to share personal data. In other words, Transcript Online and Amberscript can start transcribing immediately since all agreements around privacy legislation have already been arranged with VU Amsterdam in advance.

## Transcription method

Transcriptions can be created in an automated way by a tool or produced by a human transcriber. 

- Transcript Online offers human-edited transcription
- Amberscript offers both automated transcription and human-edited transcription

## Transcription types

Transcription is possible as verbatim, literal and automated transcription. 

- **Verbatim** transcription: Hesitations, faltering and silences are not noted and the transcriber delivers a running text. This is mainly used for informal conversations and is not always useful for scholarly research. 
- **Literal** transcription: Notes all hesitations, faltering, slips and silences. This gives a better understanding of how the conversation took place. This is the type of transcription used for legal and research purposes.
- **Automated** transcription: Uses software to convert speech to text within a few minutes, after which researchers can check the transcription for themselves, and if necessary, adjust it. Automated transcription falls in the middle between verbatim and literal transcription. The software will not transcribe short hesitations, but an emphatic "eeuhm", sigh or silence will be noted. Although the software distinguishes between different speakers, automated transcription has difficulty transcribing larger groups or voices that speak at the same time. The transcribed text will be delivered in the speakers' language.

Transcript Online offers both verbatim and literal transcriptions.

Amberscript offers verbatim, literal and automated transcriptions.

### How to choose a transcription type

The choice between different the types of transcription depends on the type of research and budget. When transcripts are not used as data but convey an idea or event, verbatim transcription or automated transcription is sufficient. When the transcription becomes the basis for exact data, such as legal, linguistic or psychological research, literal transcription is required. Even in cases requiring detailed transcripts, **automated transcription** can still be used as a starting point, provided that the researcher carefully reviews and corrects the output to ensure accuracy.

## Costs

Transcript Online and Amberscript offer paid services. Their costs are detailed below.

### Transcript Online costs

At Transcript Online, experienced transcribers convert speech into both verbatim and literal transcriptions. 

- Services: Verbatim and literal transcription
- Languages: Dutch, English and Flemish
- Delivery time: 3 - 5 working days

Costs:

| Type     | Rate per transcribed minute | Focus groups (>4pers.) | With timestamps      | Different language (+0,80) (English/Flemish) |
|----------|-----------------------------|------------------------|----------------------|----------------------------------------------|
| Verbatim | €2,25                       | + €0,30                | Every 5 min. +€0,15  | €3,05                                        |
| Literal  | €2,50                       | + €0,30                | Every 5 min. + €0,15 | €3,30                                        |

Usage: Call [Transcript Online](https://transcriptonline.nl/) for a quote and delivery time. In addition, files to be transcribed can be uploaded directly to their [website](https://transcriptonline.nl/uploaden).

### Amberscript - Automated transcription costs

Amberscript offers automated transcriptions based on their speech-to-text software.

- Services: Automated transcription 
- Languages: 39+ languages 
- Delivery time: < 60 minutes 
- Costs: 0.25 euros per minute
- Amberscript sells credits for 15 euros per transcribed hour. For new users the first 15 minutes are free. 

Usage: Log in to [Amberscript](https://www.amberscript.com/en/) via `Login with SSO`, select `Vrije Universiteit Amsterdam` and log in with your VUnetID.

### Amberscript - Human-edited transcription costs

At Amberscript, experienced transcribers convert speech into both verbatim and literal transcriptions.

- Services: Verbatim and literal transcription 
- Languages: 18 languages 
- Delivery time: 3 working days on average, urgent transcription possible within 24 hours
- Costs: On quotation, starting at €2,10 per transcribed minute 

Usage: Log in to [Amberscript](https://www.amberscript.com/en/) via `Login with SSO`, select `Vrije Universiteit Amsterdam` and log in with your VUnetID. Request a [quote](https://www.amberscript.com/nl/offerte-opvragen/) from Amberscript.
