---
title: SciStor
categories: [Data Storage]
image: '/public/VU-logo-nobg.svg'
aliases:
    - "/topics/scistor.html"
    - "/manuals/scistor/index.html"
---
## What is it?

The storage service SciStor is intended for cheaply storing large amounts of research data on campus.

SciStor is hosted by IT for Research (ITvO) on the VU campus enabling a high-speed connection to lab equipment, laptops and workstations, the [ADA HPC cluster](/tools/ada/index.qmd) and [SciCloud](/tools/scicloud/index.qmd). It can also be accessed off-campus.

Your data is stored in a **project folder** with group-based access rights (read/write or read-only). Access rights can be set one level deep, so one folder could be used to host data from different subprojects.


## What can it be used for?

### Networked Drive

Because SciStor is connected to the VU on-campus network you can directly mount (map a network drive) SciStor project folders on your laptop and work as if the data is on a local disk.

### Access off-campus

Although SciStor is most useful on campus you can also access your project folders off-campus via [EduVPN institute access](https://vu.eduvpn.nl/).

### Lab instruments

In many cases lab equipment can write data directly to SciStor. [IT for Research](mailto:itvo.it@vu.nl) can help you setup an automated and secure connection.

### Storage space for SciCloud servers

[SciCloud](/tools/scicloud/index.qmd) virtual servers are provisioned with a 20 to 50GB local disk. A SciStor project folder can be directly mounted on the server to increase storage for your application or directly access your source data for analysis.

### ADA
The [ADA HPC cluster](/tools/ada/index.qmd) is connected to SciStor via a high speed network. You can run your analysis software directly on your data and easily access the results on your laptop.

### Sharing data

Because SciStor is mainly intended for high performance, on-campus use, access is only possible with a VUnetId. If you need to share data with non-VU researchers you could [register them as an external employee](https://vu.nl/en/employee/start-employment-contract/onboarding-external-employees) or host a copy of the data on another storage platform like [Research Drive](/tools/researchdrive/index.qmd) or [Yoda](/tools/yoda/index.qmd)

### Data life-cycle

SciStor is meant for data you are actively working with. We recommend archiving datasets that are no langer actively used, but can't be deleted, in [Yoda](/tools/yoda/index.qmd). This ensures SciStor is used optimally and costs are kept down for your research group and the VU.


### Data Recovery

SciStor offers a snapshot-based data protection mechanism. There are several types of snapshot policies available:

| **Snapshot Type**      | **Description**                                                              |
|------------------------|------------------------------------------------------------------------------|
| **Daily Snapshots**    | Automatically taken every day and retained for 1 week (1d:1w)                |
| **Weekly Snapshots**   | Taken once a week and retained for 4 weeks (1w:4w)                           |
| **Custom Policies**    | Available upon request via ITvO                                              |
| **Storage Location**   | Snapshots are stored within the same scistor project folder, allowing quick recovery  |

::: {.callout-caution}
Snapshots take space within the project folder, if you delete large amount of data, be mindful that snapshots will occupy the space of the deleted data until they are expired.
:::

Snapshots act like “photo moments” of your data, enabling you to restore previous versions. Users can recover their own data by following these [instructions](snapshots-data-recovery.qmd#overview).

