---
title: Connect to SciStor
categories: []
description: 'How do I connect to SciStor?'
---


## Overview

To connect to SciStor, on- and off-campus, you need EduVPN installed with institute access.

### eduVPN
The easiest way is to install the app for [eduVPN institute access](https://vu.eduvpn.nl/portal/home). Once the VPN is active you can follow the steps below. Note that performance over the internet is limited, you might run into problems when editing large files. If needed copy them to you local disk.

## Instructions

### MacOS

1. Open the Finder application
2. In the "Go" menu, pick "Connect to Server..." or press  "⌘K"
3. Fill in: `smb://scistor.vu.nl/shares`
4. Click "Connect"
5. Select "Registered User" if this is not yet selected
6. Fill in your VUnetID and password
7. Press "Connect". Optionally, tick the "Remember this password in my keychain" checkbox. After doing this, macOS will no longer ask for credentials the next time this connection is used.

SciStor project folders appear on the left after opening the SciStor location. You may open the desired SciStor project folder by double-clicking it.

### Windows

1. Open Windows File Explorer
2. Right-click on This PC and choose "Map network drive...""
3. Select a desired drive letter, for example S. In the Folder field you can enter the following:  `\\scistor.vu.nl\shares\<the name of the project folder>`. Make sure the checkboxes are checked.
4. Click "Finish"
5. You will now be asked to log in. This is not possible with your PIN code. Choose the "More choices" option, and log in with your VU email address and password

### 'Green' Linux workspaces

Green Linux workplaces (supported by VU IT) have a connection to SciStor from home. All SciStor project folders can be found under the path `/research`.

### Other Linux workstations

Other self-managed Linux workstations can connect to SciStor via the Samba protocol:

```bash
$ sudo apt install cifs-utils
$ sudo nano /etc/credentials/<vunetID>
    # nano
username=<vumail@vu.nl>
password=<your-vunet-password> # you can put you password for convinence, otherwise you have to type your password everytime.
$ sudo mkdir -p /data/VU/shares/<name-of-your-folder>
$ sudo mount -t cifs //scistor.vu.nl/shares/<name-of-your-folder> /data/VU/shares/<name-of-your-folder> -o credentials=/etc/credentials/<vunetID>
```


The scistor project folder will be mounted at location: `/data/VU/shares`. To unmount it, simply do:

```bash
$ sudo umount /data/VU/shares/<name-of-your-folder>
```
::: {.callout-note}
the path `/data/VU/shares` is  just a suggestion, you can choose any mount path that suits your setup.
:::


