---
title: Interpreting Similarity Scores
categories: []
description: "This page provides information on interpeting the results of the similarity report."
---

iThenticate does not directly assess the presence of plagiarism in submitted works. Instead, it compares submissions to an extensive database. If similarities or matches are identified between submissions and the content within our database, the system will generate a notification for the supervisor to evaluate. The iThenticate database encompasses billions of web pages, including both current and archived internet content. Additionally, it comprises a repository of submissions made by other students, along with an assortment of documents from various sources, such as periodicals, journals, and publications.
The interpretation of the similarity report should therefore be done by a supervisor who is familiar with the established plagiarism policies.

## Information for PhD students

The iThenticate tools checks your uploaded work against a database that contains millions of sources. It is therefore normal that matches are found, especially if you've used quotes and referenced correctly. The similarity score simply highlights any matching areas in your work so your supervisor can use this as an investigative tool to determine if the match is or is not acceptable. You can apply advanced settings to ensure that the report meets the faculty's requirements.

## Information for supervisors

The Similarity Report is a dynamic document that offers a synopsis of text matches found in submitted work when compared to an extensive database of online sources, academic publications, and previously submitted documents. This tool enables PhD students and instructors to examine similarities between the submitted work and online materials. The percentage presented in a student's submission, referred to as the similarity index or similarity score, indicates the extent to which their work matches content from the database. However, this percentage should not be taken as a definitive indicator of plagiarism. The report may show matches to correctly cited and appropriately used sources, making it imperative for the instructor to apply their academic judgment in evaluating these matches. 

## Icon’s interpretation

The report icon's colors can be adjusted, to allow for easier reading of the paper's similarity score, determined by the extent of matching or similar text found. The score ranges from 0% to 100%. The allocated colors do not have to match the colors that are decided upon by the faculty, as users can apply their color schemes individually. Facilitate easy reading by applying colors to categories, for example:

<span style="color:blue;">Blue</span>: No matching text  

<span style="color:green;">Green</span>: 1–24% matching text 

<span style="color:gold;">Yellow</span>: 25–49% matching text 

<span style="color:orange;">Orange</span>: 50–74% matching text  

<span style="color:red;">Red</span>: 75–100% matching text


The report can show high matches that stem from quotes, references or previously uploaded documents. To exclude such matches in the report, advanced settings can be applied.
It is important to note that iThenticate will show a high percentage of matching text when the student has previously uploaded their work to the database. This can be addressed by applying advanced settings, such as excluding specific sources or excluding by word number.
