---
title: SciSure
categories: [Lab Journal]
image: '/public/scisure-logo.svg'
aliases:
    - "/topics/scisure.html"
---

## What is it?

SciSure, previously known as eLabNext, is an application that supports researchers with documenting experiments and results in a digital lab journal. The SciSure platform is hosted by the company SciSure. 

SciSure is used by three faculties at VU Amsterdam: BETA, FGB and ACTA. If you are interested in using SciSure, but it is not yet available in your department, please contact your VU organisational admin to discuss the possibilities.

## What can it be used for?

SciSure is used as a digital lab journal where you can track your results and share data recorded in experiments in the electronic lab notebook. 
Experiments are organised by projects; each project can contain multiple studies. SciSure can also be used to document your inventory, e.g. samples. 
Next to this, SciSure can be used to create and share protocols and to register and book equipment.