---
title: Second Handbook Hackathon
date: "2024-09-05"
author:
  - Alex van der Jagt
  - Chris Hartgerink
  - Elisa Rodenburg
  - Jens de Bruijn
  - Jolien Scholten
  - Joy Jiayi Cheng
  - Lena Karvovskaya
  - Meron Vermaas
  - Peter Vos
  - Stephanie van de Sandt
  - Tycho Hofstra
categories: ["Handbook","Hackathon"]
---

On September 5th, 2024, all authors participated in the second hackathon for the Research Support Handbook. For this hackathon, we focused on quality assurance. Quality assurance is crucial in ensuring that all parties at VU Amsterdam feel confident adopting this evolving, community-led resource as an official university page. Our goal is to migrate the handbook to rdm.vu.nl in the near future, which requires us to everything is in tip-top shape.

Collectively, we proofread the migrated LibGuide pages. The result of this are seven GitHub issues and nine pull requests for revisions. These include [making sure all images are migrated into the handbook](https://github.com/ubvu/open-handbook/issues/125), [ensuring appropriate page titles](https://github.com/ubvu/open-handbook/issues/124), and [refining the contribution guide](https://github.com/ubvu/open-handbook/issues/131).

During the hackathon, we observed a lot of links in [the old LibGuide resource](https://libguides.vu.nl/rdm), are broken. We did some much needed  maintenance work during the hackathon, given that the Research Support Handbook will replace the LibGuide resource. We identified broken links and replaced them where possible. There is a need to make this a less manual process in the future and will seek out automations to help us maintain the links moving forward. Additionally, there are many internal links that need updating, changing from LibGuide URLs to GitHub pages. We also discovered several links accessible only with university credentials, which we believe detract from the user experience; these links will require special labeling and contextualization.

The general sentiment at the end of the hackathon is that there is still lots of work to do. The community standards are manifesting themselves, and it is clear that pathways need more work to be production ready. These discussions surfaced a wish to have more frequent hackathons at this time, until the standards are set and the included content is ready for rdm.vu.nl.

## Hackathon Issues

* <https://github.com/ubvu/open-handbook/issues/123>
* <https://github.com/ubvu/open-handbook/issues/128>
* <https://github.com/ubvu/open-handbook/issues/125>
* <https://github.com/ubvu/open-handbook/issues/124>
* <https://github.com/ubvu/open-handbook/issues/123>
* <https://github.com/ubvu/open-handbook/issues/130>
* <https://github.com/ubvu/open-handbook/issues/131>

## Hackathon Pull Requests

* <https://github.com/ubvu/open-handbook/pull/126>
* <https://github.com/ubvu/open-handbook/pull/110>
* <https://github.com/ubvu/open-handbook/pull/127>
* <https://github.com/ubvu/open-handbook/pull/129>
* <https://github.com/ubvu/open-handbook/pull/132>
* <https://github.com/ubvu/open-handbook/pull/133>
* <https://github.com/ubvu/open-handbook/pull/134>
* <https://github.com/ubvu/open-handbook/pull/135>
