---
title: Fifth Handbook Hackathon
date: "2024-11-28"
author:
  - Lena Karvovskaya
  - Jolien Scholten
  - Kostas Vilkelis
  - Tycho Hofstra
  - Irene Martorelli
  - Peter Vos
categories: ["Handbook","Hackathon"]
---

On November 28, 2024, all authors participated in the fifth hackathon for the Research Support Handbook. For this hackathon, we focused on adding new content and consolidating requests.

We had a large number of contributions related to tools. The handbook now has information about Research Cloud, SciCloud and Yoda. These were long-standing issues and it is really nice that they turned into topics.

Irene helped us to revise the metadata topic.

Tycho is working on a page for ORCID, the [ORCID Libguide page](vu.nl/orcid) will be adjusted to redirect to the handbook.

Lena was working on a data backup topic, trying to make it generic and applicable to multiple tools.

We had a discussion of an overview page. New colleagues also within support miss an overview of the services available.
There are many pages that give some ideas: [the RDS portal on Tools](https://vu.nl/en/about-vu/divisions/university-library/more-about/rdm-tools), the [guide on available services](https://deploy-preview-274--ubvu-open-handbook.netlify.app/guides/data-lifecycle) and [RISP](https://vu.nl/en/research/portal/research-impact-support-portal) - but all these overviews have diverse struggles so we are still looking for a good way of doing it.

ITvO colleagues noticed that they miss an official VU page which gives a summary of what ITvO is and does.

Question that came up: how to add new contributors? Do they need access rights? Do they work with forks or branches?

## Hackathon Issues

<https://github.com/ubvu/open-handbook/issues/275>

## Hackathon Pull Requests

<https://github.com/ubvu/open-handbook/pull/277>

<https://github.com/ubvu/open-handbook/pull/276>

<https://github.com/ubvu/open-handbook/pull/140>

<https://github.com/ubvu/open-handbook/pull/273>

Merged <https://github.com/ubvu/open-handbook/pull/270#pullrequestreview-2467652120>
