---
title: Third Handbook Hackathon
date: "2024-09-30"
author:
  - Alex van der Jagt, FGB, sec. KNOP
  - Chris Hartgerink (host)
  - Diogenes Cruz de Arcelino
  - Elisa Rodenburg, UBVU
  - Jessica Hrudey, FGB
  - Jolien Scholten, UB
  - Lena Karvovskaya, UBVU
  - Stephanie van de Sandt, UBVU
  - Tycho Hofstra, UBVU
categories: ["Handbook","Hackathon"]
---

In the third hackathon for the Research Support Handbook, held on September 25th, 2024, contributors gathered to make significant progress towards migrating the handbook to the VU domain (rdm.vu.nl). The event centered around sprinting to a finish line by refining existing content and ensuring accessibility standards are met.

Key activities included:

1. **Proofreading and Topic Refinement**: Participants reviewed existing topics to ensure clarity and focus. This led to the realization that some topics, like "Data Publication," would benefit from being split into more specific subtopics, such as "Open Science" or "Software Licensing."

2. **Guide Titles Revision**: We started normalizing guide titles into questions, making navigation easier and more value informed. We ideated options for guides now titled "Plan & Design" to be converted into actionable questions like "How do I plan for managing my data?"

3. **Alt Text Improvement**: We reviewed existing alt texts for images and refined them to ensure accessibility. We also identified some remaining images that had no alt text, and added it.

4. **Image Selection**: Contributors identified and proposed openly licensed images to enhance the visual appeal of the guides, with some creative choices from [Zenodo’s RDM LEGO collection](https://doi.org/10.5281/zenodo.11147887) [@bres_2024_11147887].

Overall, the hackathon was a productive session, and the handbook is now in its final stage, with the team preparing for the official launch on <rdm.vu.nl>. In next hackathons, we may focus on splitting existing topics and adding new ones, as our list of idea topics is growing rapidly.

## Hackathon Issues

<https://github.com/ubvu/open-handbook/issues/175>
<https://github.com/ubvu/open-handbook/issues/178>

## Hackathon Pull Requests

<https://github.com/ubvu/open-handbook/pull/118>
<https://github.com/ubvu/open-handbook/pull/165>
<https://github.com/ubvu/open-handbook/pull/176>
<https://github.com/ubvu/open-handbook/pull/177>
<https://github.com/ubvu/open-handbook/pull/179>
<https://github.com/ubvu/open-handbook/pull/180>
<https://github.com/ubvu/open-handbook/pull/181>
<https://github.com/ubvu/open-handbook/pull/184>
<https://github.com/ubvu/open-handbook/pull/186>
<https://github.com/ubvu/open-handbook/pull/188>
