---
title: Data Storage Finder and Data Classification Tool unavailable
date: "2026-09-02"
author: 
  - Jolien Scholten
categories: ["Handbook"]
---

The Data Storage Finder and the Data Classification Tool are currently unavailable due to content migration of the VU website. Communication and Marketing is aware of the situation. They will make sure that these resources will be available again on September 24.

In the Data Storage Finder, you can find information about data storage tools available at VU Amsterdam. With various filters you can find the storage platform that is most suitable for your research data. It's very unfortunate that this support is unavailable at the moment, but note that extensive information about the tools we support is also available in the {{< var title >}}. You can find this information per tool (Research Drive, SciStor, Yoda) in the [Tools section](https://rdm.vu.nl/tools.html#category=Data%20Storage). If you need help with finding the right storage platform, please reach out to the [RDM Support Desk](mailto:rdm@vu.nl).

In the Data Classification Tool, you can determine the classification of your data for the criteria of availability, integrity and confidentiality. If you wish to classify your data in the short term, you can estimate this with the help of the [Data Classification Policy](https://rdm.vu.nl/public/policies-regulations/Dataclassificatiebeleid-VU-NL-v1.0.pdf) (in Dutch), which includes a table ("Bijlage 1") giving examples for the classification levels for each criterion. If you need help with this, please reach out to the [RDM Support Desk](mailto:rdm@vu.nl).

We're sorry for the inconvenience. 

Because of the content migration, other URLs may have changed as well. We're trying our best to update these as soon as we can. If you see any dead links related to RDM information, you can help us by letting us know at [rdm@vu.nl](mailto:rdm@vu.nl) or by [suggesting an edit](https://rdm.vu.nl/contributing.html). Thank you very much in advance!
