---
title: Saving, sharing and exporting results
categories: []
---

The scan will be saved in the chosen folder enabling the PhD candidate to revisit the scan results. You can share the scan, for instance with the key user iThenticate via the ‘sharing’ option after selecting the folder at the iThenticate start screen. You can find more information on inviting collaborators [here](https://guides.ithenticate.com/hc/en-us/articles/27835703903757-Sharing-folders). 

The person(s) you want to share the results with needs to have an iThenticate account. All key users iThenticate have an iThenticate account. If you want to share the results digitally with a person without an iThenticate account (for instance your (co-)supervisor), you can save the scan results as PDF file via the print icon in the bottom left corner in de detailed view. Note that reviewing the results together with your supervisor is easiest by viewing your iThenticate account together, either physically or by sharing your screen in an online meeting. 
!(public/manuals/ithenticate/9.png)

