---
title: Key Users
categories: []
description: "This page provide contact information about key users of the VU faculties." 
---

| Faculty's name | Contact adress |
| -------------  | -------------|
| Academic Center for Dentistry Amsterdam (ACTA)   |  You can find more information [on this LibGuide page](https://libguides.vu.nl/c.php?g=714180&p=5167373). |
| VUmc School of Medical Sciences (MED)   | promoties-decanalezaken@vumc.nl |
| Faculty of Social Sciences (FSW)  |  ithenticate.fsw@vu.nl |
| Faculty of Behavioural and Movement Sciences (FGB)   | You can find more information [on this LibGuide page](https://libguides.vu.nl/c.php?g=714180&p=5167373). |
| Faculty of Humanities (FGW)   |  You can find more information [on this LibGuide page](https://libguides.vu.nl/c.php?g=714180&p=5167373). |
| School of Business and Economics (SBE)   | ithenticate.sbe@vu.nl |
| Faculty of Religion and Theology (FRT)   |  You can find more information [on this LibGuide page](https://libguides.vu.nl/c.php?g=714180&p=5167373). |
| Faculty of Law (RCH)   | You can find more information [on this LibGuide page](https://libguides.vu.nl/c.php?g=714180&p=5167373). |
| BETA - Physics & Astronomy (PA)  | You can find more information [on this LibGuide page](https://libguides.vu.nl/c.php?g=714180&p=5167373).  |
| BETA - Health Sciences (HS)  | You can find more information [on this LibGuide page](https://libguides.vu.nl/c.php?g=714180&p=5167373).     |
| BETA - Mathematics (MATH)  | You can find more information [on this LibGuide page](https://libguides.vu.nl/c.php?g=714180&p=5167373).     |
| BETA - Neurosciences (AN) | hf-neurowetenschappen.beta@vu.nl |
| BETA - Athena (AI)  |  secretariaat.athena.beta@vu.nl  |
| BETA - Institute for Environmental Studies (IES)  | You can find more information [on this LibGuide page](https://libguides.vu.nl/c.php?g=714180&p=5167373).     |
| BETA - Earth Sciences (ES) | hf-aardwetenschappen.beta@vu.nl   |
| BETA - A-Life/Ecological Sciences (ECSC)  | secretariat.a-life.beta@vu.nl   |
| BETA - Computer Science (CSCI)  | informatica.secretariaat.beta@vu.nl  |
| BETA - Chemistry & Pharmaceutical Sciences (CPS)  | secretariaat.sf.beta@vu.nl   |
| BETA - Faculty of Science (BETA-MCB)  | secretariaat.mcb.beta@vu.nl |
| BETA - Environment & Health (EH)  | secretariaat.eh.beta@vu.nl |
