---
title: Costs and Getting Access
---

## How to request access
You can request access via a form on the 🔒[SURF service desk portal](https://servicedesk.surf.nl). There are 2 options:

### **1. Direct institute contract**

The VU has a contract with SURF for the usage of Snellius. Every VU researcher or master student can request Snellius SBUs (System Billing Units). The total amount available to the VU is limited however, only use this option for smaller projects, say up to 1.000.000 CPU and/or GPU SBUs.

The [SURF wiki](https://servicedesk.surf.nl/wiki/display/WIKI/Estimating+SBUs) provides some guidance on estimating the amount of SBUs you need. We recommend you start with the default 50.000 CPU and/or GPU SBUs. You can use the same form to request a top-up if you run out.

### **2. NWO compute grant**

If you have a large project involving more than 1.000.000 CPU and/or GPU SBUs you should apply for an [NWO Large Compute applications grant](https://www.surf.nl/en/large-compute-applications-nwo).

Each Snellius account is provided with 200GB Home space (backups available), apart from that 8TB of temporary fast _scratch_ space is available for your calculations. If the Home space is not sufficient or you can request _Project Space_ to store your data during your project. Note that the _Project Space_ is not backed-up! Always make sure a copy of valuable data is also stored on a [recommended storage system](/topics/data-storage.qmd).

Note that for large-scale GPU projects access the European [LUMI](https://www.surf.nl/en/services/lumi) supercomputer can also be requested by VU researcers. [Obtaining compute time on LUMI](https://servicedesk.surf.nl/wiki/display/WIKI/Obtaining+compute+time).

## Are there costs involved?
There are no direct costs for researchers, but be aware that "Direct institute contract" usage costs are billed to the faculties via KDM ("Kosten Doorbelasting Model").
