---
title: VU Compute Hub # Add link to this page to ./tools.qmd
categories: [Compute] # categories appropriate to this tool
image: '/public/logo-jupyterhub.svg' # Make sure to add a log
aliases:
    - "/topics/compute-hub.html"
---

## What is it?
The [VU Compute Hub](https://hub.compute.vu.nl) is a [JupyterHub](https://jupyter.org/hub) instance hosted by IT at  VU Amsterdam. It allows you to run a number of common analysis tools on a server. The Hub is mainly aimed at providing environments for student courses, but is available for VU researchers as well.

## What can it be used for?
The VU Compute Hub is a great environment to try if your analysis takes too much time on a laptop. It allows you to use the graphical tools you are familiar with in an environment with more compute power where you can leave your script running until it is finished.

Since every VU researcher can just log in, the barrier to entry is very low.

Be aware the service is mainly aimed at education. If your scripts use a lot of resources, it might be time for you to start using a High Performance Computing (HPC) environment: [ADA](/tools/ada/index.qmd) at VU Amsterdam or the national supercomputer [Snellius](/tools/snellius/index.qmd). Please contact [IT for Research](mailto:itvo.it@vu.nl) to discuss the best options.

### Available tools
The following applications are currently available: Jupyter Notebooks, MATLAB, STATA, R Studio and QGIS.