---
title: How can you organise your own RDM Onboarding as a new PhD candidate at the VU?
description: "Learn about the RDM essentials at the VU when you join the VU or a new project."
categories: ["Discover & Initiate", "Plan & Design"]
---

## Introduction

This guide will walk you through your research data management needs from the start of your research project to the end. You can explore the information using the [PowerPoint (PDF)](../public/phd_onboarding_general_pdf.pdf) or this page.

Treat this as a jumping-off point and make sure you also check your faculty-specific policies and guidelines.

## Explore data

### Write a DMP

When starting your research, it is important to write a [Data Management Plan (DMP)](../topics/data-management-plan.qmd). In many cases, the project you work on already has a DMP—ask your supervisor or project manager. Writing a DMP will take you through the steps needed to manage your data throughout your project.

### Pre-existing datasets

During your research, it may be useful to check [which data already exists](../topics/finding-existing-data.qmd) and could support your work.

### Identifying risks

When you use any type of data, you should check its [data classification](../topics/data-classification.qmd) and use the [Data Classification Tool](https://vu.nl/en/research/dataclassification) to find out how your data should be classified and whether there are any risks regarding confidentiality, integrity or availability associated with your data.

### Using personal data

For personal data involving human subjects, such as medical data, interviews and survey data, you will need to consider a range of policies. If you plan to use such data you can:

- Consult the [Privacy Five Step Plan](https://assets-us-01.kc-usercontent.com/d8b6f1f5-816c-005b-1dc1-e363dd7ce9a5/ad3de0e7-b935-471a-8d31-51c06ba47c88/Privacy%20five-step%20plan.pdf)
- Read up on the GDPR, beginning with this [GDPR primer](../topics/gdpr.qmd)

#### Learn about de-identification

Data de-identification is the process of protecting individual privacy by removing or masking personally identifiable information from datasets, enabling you to analyse and share data. If this is done well, it should minimise (or make it impossible) to identify the individuals the data is associated with, and ensure compliance with data protection regulations.

To learn more about this, you can find this helpful [guide](https://www.rug.nl/digital-competence-centre/privacy-and-data-protection/data-protection/guide-on-data-minimization-and-de-identification-v0-2.pdf) from University of Groningen.

#### Write your Informed Consent Form (ICF) appropriately

Research that involves human participants often requires an informed consent form (ICF). An ICF is a legal and ethical document that ensures a participant voluntarily agrees to join a study after being fully briefed on its purpose, procedures, potential risks, and their right to withdraw at any time without penalty.

-   FGB researchers can use the [ICF generator tool](https://icf.rshiny.labs.vu.nl/) to create a faculty-approved form
-   Or check your [faculty ethics page](../topics/ethical-review.qmd) for ICF templates

**Contact your [faculty's privacy champion](https://vu.nl/en/employee/information-security/privacy-champions-information) for more information.**

#### Special laws for medical research

For scientific research where participants are subject to procedures or are required to follow rules of behaviour, the Medical Research Involving Human Subjects Act (WMO) may apply.

In such cases, check whether your research is subject to the [WMO](https://english.ccmo.nl/investigators/legal-framework-for-medical-scientific-research/your-research-is-it-subject-to-the-wmo-or-not).

**Some research may require a non-WMO declaration:**

- You may need a non-WMO statement/approval from a recognised METC (for example, for publication).
- A non-WMO statement is not ethical approval; check with your faculty ethics committee whether you need to undergo a full ethical review.

*Resource: [WMO research – METC](https://metc.amsterdamumc.org/wmo/wmo-onderzoek/)*

You should also check whether any additional [medical research laws](https://english.ccmo.nl/investigators/legal-framework-for-medical-scientific-research/laws) apply.

### Ethical requirements

For some research, it is important to consider ethical requirements. To find out more, review the [faculty requirements](../topics/ethical-review.qmd) and have a look at [NETHICS](https://nethics.nl/) and the WMO/METC guidance in [Special laws for medical research](#special-laws-for-medical-research). To obtain ethics clearance, your faculty usually requires documents such as a DMP, GDPR registration, a privacy statement, an informed consent form, and a participant information sheet.

See [Ethical Review](https://vu.nl/en/research/portal/research-impact-support-portal/ethical-responsibilities#Ethical%20review) to find your faculty-specific review boards.

## Register and prepare

In some fields, it is important to pre-register your research. Preregistration is the documenting of your research plan, hypotheses, and analysis methods in a public registry before collecting or analyzing data. It is primarily used to ensure transparency and rigor in the scientific process.

### Pre-register your research

See [How to use OSF in your research project](../guides/use-osf.qmd#osf-information-for-new-users)

## Collaboration

### Roles and responsibilities

- Define roles and responsibilities **early and clearly**.
- Which data does each recipient have access to, and what are they allowed to do with it?

### Agreements

- Based on the recipient’s role, draw up the necessary agreements.
- See [Forms you may need](#forms-you-may-need) for examples of external agreements you might need.

### Legal requirements

#### Knowledge Security

When performing research at the VU, it is important to consider knowledge security. Some potential issues that may come up are:

- The undesirable transfer of sensitive information impacting the Netherlands’ national security.
- Covert influencing of education and research by dangerous state actors
- Collaboration with individuals and institutions from countries that do not respect fundamental rights

For a PhD student, the most important situations when you need to consult the knowledge security framework are:

- Inviting guest researchers or hosting guests for some time
- Intending to draw up a collaboration agreement (NDA, MoU, LoI, contract or otherwise)
- Conduct research and/or write a scientific article with colleagues of a foreign institution (co-authorship)
- If you are offering professional support with any of the above

For a full list of important situations and an in-depth explanation, see the [Knowledge security page](../topics/knowledge-security.qmd) in this handbook. If needed, contact the [VU knowledge security advisory group](mailto:kennisveiligheid@vu.nl) for advice.

### Valorisation

When you share your research with the public, you must consider intellectual property, contracts and consortium agreements. For more information, you can contact [IXA](https://vu.nl/en/about-vu/organisations/ixa-go).

- Helps with intellectual property by setting up [patents and copyrights](https://vu.nl/en/employee/research-support/protecting-your-research).
- If you work on a project with organisations outside the VU, there may be a consortium agreement or other contracts. First check with your supervisor or project manager. If there are issues, or if a new consortium agreement or contract needs drafting, you can get [legal support](https://vu.nl/en/research/portal/research-impact-support-portal/check-legal-support#Contracts).

## Forms you may need

#### Assessments

- [Data Protection Impact Assessment (DPIA)](../guides/comply-with-gdpr.qmd#complete-a-data-protection-impact-assessment-dpia)
- Pre-DPIA
- BIV

#### Legal Requirements

- [Privacy Statement](../guides/comply-with-gdpr.qmd#privacy-statement)
- [GDPR registration](../guides/comply-with-gdpr.qmd#register-your-processing-activities)
- Informed Consent Form

#### External Agreements

- Joint Controllers Agreement
- Data Processing Agreement (DPA)
- Data Transfer Agreement (DTA)
- Confidentiality agreement

*Contact your [faculty's privacy champion](https://vu.nl/en/employee/information-security/privacy-champions-information) for more information*

## Determine technical & storage solutions

### Storage Solutions

Depending on legal requirements, the size of the data, and who needs access, different storage platforms may be most suitable. You can find out more about the different platforms at the VU in [Collect & Store](../guides/collect-and-store.qmd).

### IT for Research

For research, specialised IT solutions may be required. For example, when performing heavy computations, the VU has computational clusters available. To find out more about various IT solutions, go to [IT for Research](../topics/itvo.qmd).

## Conduct your research

### Data Collection

See [Data Collection](../topics/data-collection.qmd)

#### Security Measures

- Determine the necessary security measures given the [**privacy risk**](https://vu.nl/en/research/dataclassification) of the data.
- Does the recipient need MFA? Full-disk encryption?

*Contact your [faculty privacy champion](https://vu.nl/en/employee/information-security/privacy-champions-information) before drawing up any contracts*

## Offboard your data

### Archiving & Publishing

See [Data Archiving and Publishing](../guides/publish-and-share.qmd)

#### Provide with your research data:

- **Standard metadata:** see [YODA metadata](../manuals/yoda/using_yoda/workflow_metadata.qmd)
- **Contact information for data access requests:** include long-term information, such as who should be contacted for data deletion after 10 years

**Is the project continuing at the VU but you are leaving? Then provide:**

- **Project location details:** where to find your data
- **Access to your data repositories**

### Deleting your data

**Delete your data from all non-archival repositories and software, including:**

- Castor
- ResearchDrive
- Qualtrics
- Your local computer
- Any other software, tool or repository where data is stored that is not specifically for archiving purposes

**If you cannot delete the data yourself, you can contact the [RDM Support Desk](mailto:rdm@vu.nl) to be put in contact with the functional manager for deletion**

**Prior to deletion, ensure all data you plan to delete has been exported and archived to the proper repository**

## Funding for new projects

During your project or after it has finished, you may want to explore funding opportunities to continue your research. You can find some links to get started below:

[VU IXA-GO](https://vunl.sharepoint.com/sites/ResearchFundingValorisation):

-   Helps you to identify and secure **external funding**
-   Provides **workshops** and **trainings**
-   Offers personalised **funding scans** from VU grants office
-   Offers a **CV scan** to increase competitiveness in securing related grants

[Research Connect](https://myresearchconnect.com/):

- Is a broad platform to find **external funding**
- Offers complementary services to **customise funding search**

The [Centre for International Cooperation (CIS)](https://vu.nl/en/about-vu/research-institutes/centre-for-international-cooperation/more-about/grant-and-project-management-services-for-vu-staff) offers **specialised grant advice** for projects with an international focus in:

-   Food and Nutrition and Sustainable Land Management
-   ICT for Development
-   Conflict Resolution and Mediation and Governance for Society (incl. Security & Rule of Law)

## Contact information

For any further questions, you can find the most important points of contact below.

### General RDM support:

[The RDM Support Desk](mailto:rdm@vu.nl)

### Faculty specific data stewards:

[Contact your data steward](https://vu.nl/en/employee/research-data-support/contact-your-data-steward)

### Faculty specific privacy champions:

[Privacy champions](https://vu.nl/en/employee/policy-and-organisation/privacy-champions-information)
