---
title: How can you organise your own RDM Onboarding as a new PhD candidate at the VU?
description: "Learn about the RDM essentials at the VU when you join the VU or a new project."
categories: ["Discover & Initiate", "Plan & Design"]
---


## Introduction

The following guide will walk you through you research data management needs from before the research project has begun to once your research project is over or you have left the VU. You can explore the information using the powerpoint here: or by reading through each of the sections on this page. Overall this information is meant to be a jumping-off point so please be sure to check your faculty specific policies and guidelines. There is also a [slide deck](../public/phd_onboarding_general_pdf.pdf) that summarises these guidelines.

## Explore funding & data


### Funding

[VU IXA-GO](https://vunl.sharepoint.com/sites/ResearchFundingValorisation):

-   Helps you to identify and secure **external funding**
-   Provides **workshops** and **trainings**
-   Offers personalised **funding scans** from VU grants office
-   Offers a **CV scan** to increase competitiveness in securing related grants

[Research Connect](https://myresearchconnect.com/):

-   Is a broad platform to find **external funding**
-   Offers complementary services to **customise funding search**

The [Centre for Internation Cooperation (CIS)](https://vu.nl/en/about-vu/research-institutes/centre-for-international-cooperation/more-about/grant-and-project-management-services-for-vu-staff) offers **specialised grant advising** for projects with an international focus in:

-   Food and Nutrition and Sustainable Land Management
-   ICT for Development
-   Conflict Resolution and Mediation and Governance for Society (incl. Security & Rule of Law)

### Pre-existing datasets

See [Finding Existing Data](../topics/finding-existing-data.qmd)


## Investigate your legal responsibilities

### Knowledge Security

#### What is it

- The undesirable transfer of sensitive information impacting the Netherlands’ national security.
- Covert influencing of education and research by dangerous state actors
- Collaboration with individuals and institutions from countries that do not respect fundamental rights

More in-depth explanation about Knowledge Security can be found on the [Knowledge security page](../topics/knowledge-security.qmd) in this handbook.

#### How does it impact you\*

The primary responsible researcher answers 6 framework questions. 

One yes = risk assessment needed (contact [faculty knowledge security officer](https://vu.nl/en/employee/onderwijs-en-onderzoeksbeleid/knowledge-security-for-vu-amsterdam-employees#:~:text=Faculty%20contact%20persons)for assistance)

If needed, they contact the [VU knowledge security advisory group](mailto:kennisveiligheid@vu.nl)for advice

*\*If you are conducting international collaborations (formal, informal, hiring, visitors)*

*See [Knowledge Security](https://vu.nl/en/about-vu/more-about/knowledge-security) for more information*

### VU Knowledge Security Framework

#### Legal framework – what is not permitted, or under conditions

1\. Does the collaboration concern a sanctioned person, entity or body? Or is the combination of the technology and country sanctioned? - See [EU sanctions list](https://www.sanctionsmap.eu/#/main).

2\. Is the Dual Use regime applicable to the research? - Contact the [KS advisory team](mailto:kennisveiligheid@vu.nl)for advice.

**Risk management – what else should be considered**

3\.  Is, or has the partner been affiliated to a military organization outside the EU?- collaboration with military organisations outside EU is undesirable.

4\. Does the collaboration involve sensitive research?

5\. Do ethical dilemmas play a role? - check if the partner is based in county which scores 0.4 or less on the [Academic Freedom Index](https://academic-freedom-index.net/).

6\. Does unilateral external funding occur in the cooperation? - Check [AFI](https://academic-freedom-index.net/)

**No limitations – cooperation can take place**

7\. There are no obstacles for the collaboration from a knowledge security perspective

### Legal Requirements

#### Valorisation & Impact

Contact [IXA](https://vu.nl/en/about-vu/organisations/ixa-go)

-   Helps with intellectual property by setting up [patents and copyrights](https://vu.nl/en/employee/research-support/protecting-your-research)
-   Assists in setting up [contracts](https://vu.nl/en/research/portal/research-impact-support-portal/check-legal-support#Contracts) with third parties (e.g. consortium agreements)

**Medical Research**

If you are conducting medical research, determine:​

-   How your research is defined by [Dutch law](https://english.ccmo.nl/investigators/legal-framework-for-medical-scientific-research/your-research-is-it-subject-to-the-wmo-or-not)​
-   Whether any additional [medical research laws](https://english.ccmo.nl/investigators/legal-framework-for-medical-scientific-research/laws)apply\

## Register & prepare

### Pre-register your research

See [How to use OSF in your research project](../guides/use-osf.qmd#osf-information-for-new-users)

### Data classification

See [Data Classification](../topics/data-classification.qmd)

### Personal data

#### Read up on policies about personal data

-   Consult the [Privacy Five Step Plan](https://assets-us-01.kc-usercontent.com/d8b6f1f5-816c-005b-1dc1-e363dd7ce9a5/ad3de0e7-b935-471a-8d31-51c06ba47c88/Privacy%20five-step%20plan.pdf)
-   Read up on the GDPR, beginning with this [GDPR primer](../topics/gdpr.qmd)

#### Assess your data’s privacy risk level

-   Use the [Data Classification Tool](https://vu.nl/en/research/dataclassification) and follow the necessary measures for risk level

#### Learn about de-identification

-   Do your best to de-identify your participants' data.
-   (See this helpful [guide](https://www.rug.nl/digital-competence-centre/privacy-and-data-protection/data-protection/guide-on-data-minimization-and-de-identification-v0-2.pdf) from University of Groningen)

#### Write your Informed Consent Form (ICF) appropriately

-   FGB researchers can use the [ICF generator tool](https://icf.rshiny.labs.vu.nl/) to create a faculty-approved form
-   Or check your [faculty ethics page](../topics/ethical-review.qmd) for ICF templates

**Contact your [faculty's privacy champion](https://vu.nl/en/employee/information-security/privacy-champions-information) for more information**

### Forms you may need

#### Assessments

-   [Data Protection Impact Assessment (DPIA)](../guides/comply-with-gdpr.qmd#complete-a-data-protection-impact-assessment-dpia)
-   Pre-DPIA
-   BIV

#### Legal Requirements

-   [Privacy Statement](../guides/comply-with-gdpr.qmd#privacy-statement)
-   [GDPR registration](../guides/comply-with-gdpr.qmd#register-your-processing-activities)
-   Informed Consent Form

#### External Agreements

-   Joint Controllers Agreement
-   Data Processing Agreement (DPA)
-   Data Transfer Agreement (DTA)
-   Confidentiality agreement

*Contact your [faculty's privacy champion](https://vu.nl/en/employee/information-security/privacy-champions-information) for more information*

## Determine technical & storage solutions

### Storage Solutions

See [Collect & Store](../guides/collect-and-store.qmd)

### IT for Research

See [IT for Research](../topics/itvo.qmd)

## Write a DMP

See [Data Management Plan (DMP)](../topics/data-management-plan.qmd)

## Determine your ethical requirements

### Ethical requirements

#### Investigate

-   [Faculty requirements](../topics/ethical-review.qmd)
-   [NETHICS](https://nethics.nl/)
-   [WMO/METc](#WMO/METc)

#### Prepare

-   The necessary documents as required by your faculty

*e.g. DMP, GDPR registration, Privacy Statement*

#### Submit

-   The required documents andethics form as per your faculty procedure

    *e.g. Informed Consent Form, Participant Information Sheet*

*See [Ethical Review](https://vu.nl/en/research/portal/research-impact-support-portal/ethical-responsibilities#Ethical%20review) to find your faculty specific review boards*.

### WMO/METc

**Research falls under the WMO if the following two conditions are met:**

-   it concerns medical-scientific research; and
-   people are subjected to procedures or are required to follow rules of behaviour

**Some research may require a non-WMO declaration:**

-   You need a non-WMO statement/approval from a recognised METC, for example for publication.
-   Non-WMO statement is not ethical approval, check with your faculty ethics committee if you need to undergo a full ethical review\

*Resource: [WMO research – METC](https://metc.amsterdamumc.org/wmo/wmo-onderzoek/)*

## Conduct your research


### Data Collection

See [Data Collection](../topics/data-collection.qmd)

### Collaboration

#### Roles & Responsibilities

-   Define the roles & responsibilities **early and clearly.**
-   Which data does the recipient have access to? What can they do with the data?

#### Agreements

-   Based of the role of the recipient, draw upthe necessary agreements:​
-   See the **Forms you may need** to find the kind of external agreements you may need.

#### Security Measures

-   Determine the necessary security measures given the [**privacy risk**](https://vu.nl/en/research/dataclassification)of the data.
-   Does the recipient need MFA? Full-disk encryption?

*Contact your [faculty privacy champion](https://vu.nl/en/employee/information-security/privacy-champions-information) before drawing up any contracts*

## Offboard your data

### Archiving & Publishing

See [Data Archiving and Publishing](../guides/publish-and-share.qmd)

#### Provide with your research data:

-   **Standard metadata:** see [YODA metadata](../manuals/yoda/using_yoda/workflow_metadata.qmd)
-   **Contact information for data access requests**: include long term information such as who should be contacted for data deletion after 10 years

**Is the project continuing at the VU but you are leaving? Then provide:**

-   **Project location data**: i.e., where to find your data
-   **Access to your data repositories**

### Deleting your data

**Delete your data from all non-archival repositories and software, including:**

-   Castor
-   ResearchDrive
-   Qualtrics
-   Your local computer
-   Any other software/tool/repository which the data can be stored and and is not where you will be archiving

**For most of these tools, contact [the RDM Support Desk](mailto:rdm@vu.nl) to be put in contact with the functional manager for deletion**

**Prior to deletion, ensure all data you plan to delete has been exported and archived to the proper repository**

## Contact information


#### General RDM support:

[The RDM Support Desk](mailto:rdm@vu.nl)

#### Faculty specific data stewards:

[Contact your data steward](https://vu.nl/en/employee/research-data-support/contact-your-data-steward)

#### Faculty specific privacy champions:

[Privacy champions](https://vu.nl/en/employee/policy-and-organisation/privacy-champions-information)
