---
title: Quick Start
---

### Accessing Pure

To work within Pure go to [the login page](https://research.vu.nl/admin/workspace.xhtml). You can log in using your VUnetID and password.

### Manage your personal profile

There is a manual available on how to manage your personal profile in Pure: [LibGuides - Personal Profile](https://libguides.vu.nl/manage-pure-profile) 
You can also [link your ORCID profile to your PURE profile](https://libguides.vu.nl/orcid/register), which has as a benefit that publications registered in PURE are automatically added to your ORCID profile.

### Adding research outputs

There is a manual available on how to register different types of research output: [LibGuides - Publications](https://libguides.vu.nl/pure-managing-publications)

There are also other related topics available in the {{< var title >}} Manuals :

- [Dataset registration in Pure](data-registration.qmd)
- [Software registration in Pure](software-registration.qmd)

Note that the [Research Data and Software Management Policy](/topics/research-data-and-software-management-policy.qmd) states that archived and published data and software must be registered. This is not done automatically. Researchers are requested to check their registrations and evaluate if they are complete. If they have archived or published data or software that has not been included in their Pure profile, they need to add these registrations themselves, as explained in the manual mentioned above.
